import {
  Activity,
  AlarmClock,
  AlertOctagon,
  AlertTriangle,
  Ambulance,
  Anchor,
  Apple,
  Archive,
  Armchair,
  Award,
  Axe,
  Baby,
  Backpack,
  BadgeCheck,
  Banana,
  Bandage,
  BarChart3,
  Bath,
  Battery,
  Beaker,
  Bed,
  BedDouble,
  Beef,
  Beer,
  Bell,
  Bike,
  Bird,
  Bone,
  Book,
  BookA,
  BookHeart,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Bookmark,
  Boxes,
  Brain,
  Briefcase,
  Brush,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  CalendarCheck,
  CalendarDays,
  CalendarHeart,
  Camera,
  Candy,
  Car,
  Carrot,
  Cat,
  ChefHat,
  Cherry,
  Church,
  CircleDollarSign,
  CircleDot,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudRain,
  Clover,
  Code,
  Coffee,
  Compass,
  Computer,
  Construction,
  Contact,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  Crown,
  CupSoda,
  Database,
  Dog,
  DollarSign,
  Donut,
  Drama,
  Droplet,
  Drum,
  Drumstick,
  Dumbbell,
  Ear,
  Egg,
  Factory,
  Feather,
  FerrisWheel,
  FileBadge,
  FileCheck,
  FileText,
  Film,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  Flashlight,
  Flower,
  Flower2,
  Folder,
  Footprints,
  Forklift,
  Fuel,
  Gamepad2,
  Gauge,
  Gavel,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Grape,
  Hammer,
  HandCoins,
  HandHeart,
  HandHelping,
  Handshake,
  HardHat,
  Headphones,
  Headset,
  Heart,
  HeartHandshake,
  HeartPulse,
  History,
  Home,
  Hospital,
  Hotel,
  Hourglass,
  IceCream,
  IdCard,
  Image as ImageIcon,
  Inbox,
  Infinity,
  Info,
  Joystick,
  Key,
  KeyRound,
  Keyboard,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Link as LinkIcon,
  Lock,
  Magnet,
  Mail,
  Map,
  MapPin,
  Martini,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  Microscope,
  Microwave,
  Milk,
  Monitor,
  Moon,
  Mountain,
  MountainSnow,
  Music,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  Package,
  Palette,
  Paintbrush,
  PartyPopper,
  PawPrint,
  Pen,
  PenTool,
  Pencil,
  Phone,
  PhoneCall,
  PiggyBank,
  Pill,
  PillBottle,
  Pizza,
  Plane,
  Plug,
  Podcast,
  Popcorn,
  Printer,
  Puzzle,
  Radio,
  Rainbow,
  Receipt,
  Recycle,
  RefreshCw,
  Ribbon,
  Rocket,
  Route,
  Ruler,
  Salad,
  Sandwich,
  Scale,
  School,
  Scissors,
  ScrollText,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Signal,
  Siren,
  Smartphone,
  Smile,
  Snowflake,
  Soup,
  Sparkles,
  Speaker,
  Sprout,
  Stamp,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Swords,
  Syringe,
  Tag,
  Target,
  Telescope,
  Tent,
  Terminal,
  ThumbsUp,
  Ticket,
  Timer,
  Tractor,
  TrafficCone,
  Train,
  TrainFront,
  TreeDeciduous,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Unlock,
  UserCheck,
  UserPlus,
  Users,
  Utensils,
  UtensilsCrossed,
  Vegan,
  Video,
  Volleyball,
  Volume2,
  Vote,
  Wallet,
  Wand,
  Watch,
  Waves,
  Webcam,
  Weight,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICON_REGISTRY: Record<string, LucideIcon> = {
  Activity, AlarmClock, AlertOctagon, AlertTriangle, Ambulance, Anchor, Apple, Archive, Armchair,
  Award, Axe, Baby, Backpack, BadgeCheck, Banana, Bandage, BarChart3, Bath, Battery,
  Beaker, Bed, BedDouble, Beef, Beer, Bell, Bike, Bird, Bone, Book, BookA, BookHeart,
  BookMarked, BookOpen, BookOpenCheck, Bookmark, Boxes, Brain, Briefcase, Brush,
  Building, Building2, Bus, Cake, Calculator, CalendarCheck, CalendarDays,
  CalendarHeart, Camera, Candy, Car, Carrot, Cat, ChefHat, Cherry, Church,
  CircleDollarSign, CircleDot, CircleHelp, ClipboardCheck, ClipboardList, Clock,
  Cloud, CloudRain, Clover, Code, Coffee, Compass, Computer, Construction, Contact,
  Cookie, Cpu, CreditCard, Croissant, Crown, CupSoda, Database, Dog, DollarSign,
  Donut, Drama, Droplet, Drum, Drumstick, Dumbbell, Ear, Egg, Factory, Feather,
  FerrisWheel, FileBadge, FileCheck, FileText, Film, Fingerprint, Fish, Flag, Flame,
  Flashlight, Flower, Flower2, Folder, Footprints, Forklift, Fuel, Gamepad2, Gauge,
  Gavel, Gem, Gift, Glasses, Globe, GraduationCap, Grape, Hammer, HandCoins,
  HandHeart, HandHelping, Handshake, HardHat, Headphones, Headset, Heart,
  HeartHandshake, HeartPulse, History, Home, Hospital, Hotel, Hourglass, IceCream,
  IdCard, Image: ImageIcon, Inbox, Infinity, Info, Joystick, Key, KeyRound, Keyboard,
  Lamp, Landmark, Languages, Laptop, Layers, Leaf, Library, LifeBuoy, Lightbulb,
  LineChart, Link: LinkIcon, Lock, Magnet, Mail, Map, MapPin, Martini, Medal,
  Megaphone, MessageCircle, MessageSquare, Mic, Microscope, Microwave, Milk, Monitor,
  Moon, Mountain, MountainSnow, Music, Navigation, Network, Newspaper, Notebook,
  NotebookPen, Package, Palette, Paintbrush, PartyPopper, PawPrint, Pen, PenTool,
  Pencil, Phone, PhoneCall, PiggyBank, Pill, PillBottle, Pizza, Plane, Plug, Podcast,
  Popcorn, Printer, Puzzle, Radio, Rainbow, Receipt, Recycle, RefreshCw, Ribbon,
  Rocket, Route, Ruler, Salad, Sandwich, Scale, School, Scissors, ScrollText, Search,
  Send, Settings, Shield, ShieldCheck, Ship, Shirt, ShoppingBag, ShoppingBasket,
  ShoppingCart, Shovel, ShowerHead, Signal, Siren, Smartphone, Smile, Snowflake, Soup, Sparkles,
  Speaker, Sprout, Stamp, Star, Stethoscope, Store, Sun, Sunrise, Sunset, Swords,
  Syringe, Tag, Target, Telescope, Tent, Terminal, ThumbsUp, Ticket, Timer, Tractor,
  TrafficCone, Train, TrainFront, TreeDeciduous, TreePine, Trophy, Truck, Tv,
  Umbrella, Unlock, UserCheck, UserPlus, Users, Utensils, UtensilsCrossed, Vegan, Video,
  Volleyball, Volume2, Vote, Wallet, Wand, Watch, Waves, Webcam, Weight, Wheat, Wifi,
  Wind, Wine, Wrench, Zap,
};

// Curated palette of distinct, accessible oklch colors for category icons.
export const COLOR_POOL: string[] = [
  "oklch(0.45 0.09 165)", "oklch(0.45 0.10 280)", "oklch(0.48 0.08 210)",
  "oklch(0.45 0.04 250)", "oklch(0.45 0.10 330)", "oklch(0.52 0.10 85)",
  "oklch(0.48 0.09 145)", "oklch(0.50 0.11 15)",  "oklch(0.50 0.10 70)",
  "oklch(0.50 0.10 40)",  "oklch(0.48 0.08 110)", "oklch(0.42 0.10 20)",
  "oklch(0.48 0.10 305)", "oklch(0.42 0.07 200)", "oklch(0.40 0.08 155)",
  "oklch(0.46 0.08 195)", "oklch(0.48 0.06 140)", "oklch(0.45 0.07 240)",
  "oklch(0.45 0.04 70)",  "oklch(0.55 0.11 90)",  "oklch(0.50 0.12 5)",
  "oklch(0.46 0.11 55)",  "oklch(0.50 0.10 100)", "oklch(0.46 0.10 130)",
  "oklch(0.44 0.10 175)", "oklch(0.46 0.10 220)", "oklch(0.44 0.11 260)",
  "oklch(0.46 0.12 295)", "oklch(0.48 0.11 320)", "oklch(0.50 0.10 350)",
  "oklch(0.42 0.06 30)",  "oklch(0.42 0.06 180)", "oklch(0.55 0.09 60)",
  "oklch(0.40 0.08 270)", "oklch(0.52 0.08 170)", "oklch(0.48 0.10 25)",
  "oklch(0.46 0.09 245)", "oklch(0.50 0.10 125)", "oklch(0.44 0.09 95)",
  "oklch(0.48 0.10 285)",
];

export function resolveCategoryIcon(name: string | null | undefined): LucideIcon {
  if (name && ICON_REGISTRY[name]) return ICON_REGISTRY[name];
  return Sparkles;
}

// Keywords mapped to icons. Case-insensitive substring/word matches against the title.
const ICON_KEYWORDS: Record<string, string[]> = {
  // Recovery / mental / wellness
  RefreshCw: ["reentry", "re-entry", "restart", "renew", "reset", "transition", "return", "release", "reintegration", "fresh start", "new beginning", "second chance", "supervision", "parole", "probation", "post-release"],
  Brain: ["mind", "mental", "brain", "cognitive", "psych", "therapy", "counseling", "neuro", "ptsd", "trauma", "anxiety", "depression", "bipolar", "schizophrenia", "psychiatric", "emotional", "behavioral", "mental health", "mood", "stress"],
  HeartPulse: ["health", "vital", "wellness", "pulse", "cardio", "physical health", "checkup", "monitoring", "chronic", "condition"],
  Heart: ["love", "care", "compassion", "relationship", "wellness", "emotional health", "self-love", "self-worth", "belonging", "connection"],
  HeartHandshake: ["support", "compassion", "care", "ally", "peer support", "community", "solidarity", "mutual aid"],
  HandHeart: ["care", "giving", "donate", "compassion", "volunteer", "nurture", "kindness", "generosity"],
  HandHelping: ["help", "assist", "support", "aid", "outreach", "case management", "service", "intake", "navigator", "coach"],
  Handshake: ["partner", "mentor", "agreement", "deal", "ally", "collaboration", "partnership", "trust", "relationship", "accountability"],
  LifeBuoy: ["help", "rescue", "crisis", "emergency", "support", "hotline", "988", "crisis line", "intervention", "safety plan"],
  Smile: ["happy", "joy", "positive", "smile", "wellness", "mood", "positivity", "optimism", "hope", "humor"],
  Sparkles: ["wellness", "inspire", "magic", "shine", "spark", "motivation", "inspiration", "transformation", "growth"],
  Sprout: ["growth", "new", "start", "seed", "grow", "progress", "potential", "hope", "healing", "change"],
  Sun: ["sun", "energy", "bright", "solar", "morning", "hope", "optimism", "new day", "positivity"],
  Sunrise: ["morning", "rise", "new", "dawn", "new beginning", "hope", "fresh start", "release"],
  Sunset: ["evening", "calm", "rest", "reflection", "peace", "closure"],
  Moon: ["night", "sleep", "rest", "moon", "insomnia", "rest", "calm", "quiet"],
  Bath: ["selfcare", "bath", "relax", "hygiene", "self-care", "grooming", "cleanliness"],
  ShowerHead: ["shower", "hygiene", "clean", "self-care", "grooming", "sanitation"],
  Wand: ["magic", "transform", "change", "healing", "recovery"],
  Clover: ["luck", "fortune", "lucky", "hope", "chance"],
  Rainbow: ["pride", "lgbt", "lgbtq", "diversity", "rainbow", "inclusion", "identity", "queer", "gender", "sexuality"],

  // Substance / addiction
  Wine: ["substance", "addiction", "sobriety", "recovery", "alcohol", "wine", "aa", "alcoholics anonymous", "drinking", "substance use", "dependence", "abstinence"],
  Beer: ["substance", "addiction", "sobriety", "alcohol", "beer", "drinking", "substance use"],
  Martini: ["substance", "addiction", "sobriety", "alcohol", "bar", "drinks", "substance abuse"],
  Pill: ["substance", "addiction", "sobriety", "drug", "medication", "pill", "rx", "narcotic", "opioid", "opiate", "opioid use disorder", "oud", "suboxone", "buprenorphine", "methadone", "mat", "medication assisted treatment", "prescription"],
  PillBottle: ["substance", "addiction", "sobriety", "medication", "prescription", "pharmacy", "drug", "suboxone", "methadone", "naltrexone", "vivitrol", "medication management", "mat"],
  Syringe: ["substance", "addiction", "sobriety", "needle", "injection", "drug", "harm reduction", "vaccine", "iv drug use", "narcan", "naloxone", "opioid reversal", "intravenous"],

  // Medical / healthcare
  Stethoscope: ["medical", "health", "healthcare", "doctor", "clinic", "checkup", "primary care", "physician", "provider", "physical", "exam", "telehealth"],
  Hospital: ["medical", "health", "healthcare", "hospital", "clinic", "emergency room", "inpatient", "detox", "residential", "treatment facility", "rehab"],
  Ambulance: ["medical", "health", "healthcare", "emergency", "ambulance", "ems", "911", "crisis", "acute care"],
  Bandage: ["medical", "health", "healthcare", "injury", "first aid", "wound", "first responder", "basic care"],
  Microscope: ["medical", "health", "healthcare", "lab", "research", "science", "testing", "bloodwork", "std testing", "hiv test", "hepatitis"],
  Beaker: ["medical", "health", "healthcare", "lab", "science", "test", "research", "drug test", "urinalysis"],
  Bone: ["medical", "health", "healthcare", "bone", "ortho", "skeleton", "injury", "physical therapy"],
  Ear: ["medical", "health", "healthcare", "hearing", "ear", "audio", "listen", "communication", "accessibility"],
  Glasses: ["medical", "health", "healthcare", "vision", "eye", "glasses", "optometry", "eyecare", "sight", "vision care"],
  Activity: ["medical", "health", "healthcare", "activity", "vital", "monitor", "pulse", "health tracking", "fitness", "wellness"],

  // Family / kids / parenting
  Baby: ["baby", "infant", "newborn", "parent", "parenting", "child", "pregnancy", "prenatal", "postpartum", "wic"],
  Users: ["community", "group", "team", "peer", "people", "social", "group therapy", "support group", "cohort", "network", "circle", "fellowship"],
  UserCheck: ["verified", "approved", "member", "enrolled", "participant"],
  UserPlus: ["enroll", "register", "join", "signup", "intake", "admission", "referral", "onboarding"],
  PartyPopper: ["celebration", "party", "event", "graduation", "milestone", "achievement", "success"],
  Cake: ["birthday", "celebration", "party", "milestone", "anniversary"],

  // Education / literacy
  GraduationCap: ["education", "graduate", "degree", "college", "university", "academic", "ged", "diploma", "certification", "trade school", "vocational", "higher education", "hsed", "high school equivalency"],
  School: ["school", "class", "education", "training", "k12", "adult education", "continuing education", "learning center", "classroom"],
  BookOpen: ["book", "read", "reading", "study", "education", "literacy", "guide", "adult literacy", "basic skills", "foundational", "learn"],
  BookOpenCheck: ["book", "read", "reading", "learning", "study", "education", "curriculum", "coursework", "completion", "certificate program"],
  Book: ["book", "read", "reading", "study", "education", "resource", "textbook", "manual", "learn"],
  BookA: ["book", "read", "reading", "education", "language", "dictionary", "vocabulary", "spanish", "english", "esl", "english as second language", "bilingual", "ell", "language learning"],
  BookMarked: ["book", "read", "reading", "study", "education", "bookmark", "saved", "reference", "guide"],
  BookHeart: ["book", "read", "reading", "education", "story", "favorite", "memoir", "narrative", "personal story"],
  Library: ["book", "read", "reading", "education", "library", "resource", "archive", "collection", "public library", "research", "information"],
  Pencil: ["write", "edit", "homework", "note", "writing skills", "essay", "application", "resume writing"],
  Pen: ["write", "sign", "compose", "contract", "signature", "legal document"],
  PenTool: ["design", "draw", "create", "graphic design", "digital skills"],
  Paintbrush: ["art", "paint", "creative", "art therapy", "expression"],
  Brush: ["art", "paint", "brush", "art therapy", "creative expression"],
  Palette: ["art", "creative", "design", "color", "art program", "art class"],
  Notebook: ["note", "journal", "study", "journaling", "diary", "log", "tracker"],
  NotebookPen: ["journal", "note", "write", "journaling", "reflective writing"],
  ScrollText: ["scroll", "document", "history", "record", "official document"],
  Languages: ["language", "translate", "bilingual", "interpreter", "translation", "multilingual", "esl", "spanish", "english"],
  Lightbulb: ["idea", "tip", "insight", "innovation", "learn", "solution", "strategy", "skill", "knowledge"],
  Telescope: ["explore", "discover", "vision", "future", "opportunity", "goal setting"],
  Ruler: ["measure", "ruler", "math", "basic math", "numeracy"],
  Calculator: ["math", "calc", "tax", "accounting", "number", "budgeting", "financial literacy", "numeracy"],
  Sigma: ["math", "sum", "statistics", "data", "numbers"],

  // Work / employment / trades
  Briefcase: ["job", "career", "work", "employment", "business", "professional", "job search", "job readiness", "workforce", "placement", "hiring", "occupation", "job fair", "staffing"],
  Building: ["office", "building", "company", "employer", "workplace", "work site"],
  Building2: ["business", "office", "corporate", "organization", "company", "agency", "nonprofit", "employer"],
  Factory: ["factory", "manufacturing", "industrial", "warehouse", "production", "assembly", "plant"],
  HardHat: ["construction", "trade", "labor", "safety", "osha", "skilled trade", "apprenticeship", "union", "journeyman"],
  Hammer: ["construction", "trade", "build", "repair", "tool", "skilled trade", "carpentry", "handyman"],
  Wrench: ["repair", "tool", "fix", "maintenance", "mechanic", "auto repair", "plumbing", "hvac", "trade"],
  Construction: ["construction", "build", "site", "contractor", "skilled trade", "apprenticeship"],
  Forklift: ["warehouse", "logistics", "forklift", "material handling", "distribution"],
  Shovel: ["dig", "labor", "landscape", "manual", "landscaping", "groundskeeping", "outdoor work"],
  Axe: ["forestry", "lumber", "axe", "logging", "outdoor trades"],
  ChefHat: ["chef", "cook", "culinary", "food service", "kitchen", "restaurant", "hospitality", "catering", "culinary arts", "foodservice"],
  Scissors: ["barber", "salon", "cosmetology", "hair", "cutting", "barbering", "beauty school", "nail tech"],
  Shirt: ["clothing", "uniform", "apparel", "dress", "clothing assistance", "work clothes", "interview clothes"],
  Truck: ["delivery", "trucking", "transport", "cdl", "logistics", "moving", "commercial driver", "commercial driving", "freight"],
  Tractor: ["farming", "agriculture", "tractor", "farm work", "rural"],
  Wheat: ["farming", "agriculture", "grain", "food production", "farm"],

  // Documents / ID / paperwork
  FileText: ["document", "form", "record", "report", "paperwork", "application", "forms", "filing", "documentation", "vital records"],
  FileCheck: ["verified", "approved", "complete", "filed", "processed", "confirmed"],
  FileBadge: ["certificate", "credential", "license", "certification", "diploma", "official"],
  ClipboardList: ["intake", "checklist", "task", "form", "assessment", "screening", "case plan", "service plan"],
  ClipboardCheck: ["complete", "approved", "checklist", "case review", "audit", "compliance"],
  IdCard: ["id", "identification", "license", "state id", "driver license", "real id", "government id", "photo id", "birth certificate", "social security card"],
  Stamp: ["stamp", "approve", "seal", "official", "notary", "certified"],
  BadgeCheck: ["verified", "certified", "credential", "licensed", "accredited"],
  Fingerprint: ["fingerprint", "background check", "biometric", "id", "criminal history", "rap sheet", "livescan", "clearance"],
  Receipt: ["receipt", "bill", "invoice", "payment confirmation", "proof of payment"],
  Folder: ["files", "folder", "documents", "case file", "records", "portfolio"],
  Archive: ["archive", "storage", "records", "expungement", "sealing", "record sealing", "sealed records"],

  // Legal
  Scale: ["legal", "law", "court", "justice", "rights", "attorney", "balance", "legal aid", "pro bono", "civil rights", "legal services", "public defender", "lawyer"],
  Gavel: ["legal", "law", "court", "judge", "ruling", "sentence", "expungement", "pardon", "clemency", "hearing", "trial", "plea", "charges", "conviction", "court date", "probation violation"],
  Vote: ["legal", "law", "civic", "vote", "voting", "election", "voting rights", "restoration of rights", "civic engagement", "voter registration", "suffrage", "ballot"],
  Landmark: ["legal", "law", "court", "government", "civic", "capitol", "institution", "government office", "courthouse", "city hall", "public office", "dmv", "social security office"],
  Lock: ["legal", "law", "lock", "secure", "private", "incarceration", "incarcerated", "jail", "prison", "detention", "confinement"],
  KeyRound: ["legal", "law", "access", "key", "unlock", "release", "discharge", "freedom", "open door"],
  Key: ["legal", "law", "access", "key", "unlock", "security", "reentry", "release", "opportunity"],
  Shield: ["legal", "law", "safety", "security", "protect", "defense", "insurance", "protection", "domestic violence", "safety planning", "restraining order", "shelter from abuse"],
  ShieldCheck: ["legal", "law", "protected", "secure", "verified", "safety", "safe housing"],
  Siren: ["legal", "law", "emergency", "alert", "police", "911", "crisis", "hotline", "law enforcement", "officer", "police contact"],
  AlertOctagon: ["legal", "urgent", "stop", "danger", "warning", "alert", "high risk", "critical"],
  AlertTriangle: ["legal", "warning", "alert", "caution", "risk", "trigger", "relapse warning"],
  Unlock: ["legal", "law", "release", "freedom", "fresh start", "reentry", "open", "discharge", "exonerated", "expungement", "pardon", "cleared"],

  // Finance / money / benefits
  Wallet: ["money", "finance", "benefits", "wallet", "budget", "financial", "spending", "cash management", "personal finance"],
  PiggyBank: ["money", "finance", "benefits", "savings", "save", "budget", "savings account", "emergency fund", "banking", "financial stability"],
  CreditCard: ["money", "finance", "benefits", "credit", "card", "payment", "banking", "credit building", "credit score", "bank account", "debit card", "secured card"],
  DollarSign: ["money", "finance", "benefits", "cost", "price", "dollar", "income", "wages", "earnings", "pay", "salary"],
  CircleDollarSign: ["money", "finance", "benefits", "cash", "funding", "grant", "stipend", "income", "financial assistance"],
  HandCoins: ["money", "finance", "benefits", "snap", "ebt", "assistance", "cash", "stipend", "tanf", "welfare", "food stamps", "public benefits", "cash assistance", "government assistance", "entitlements"],
  Coins: ["money", "finance", "benefits", "coins", "savings", "spare change", "emergency funds"],
  BarChart3: ["analytics", "stats", "report", "progress tracking", "outcomes", "data", "metrics"],
  LineChart: ["trend", "growth", "analytics", "progress", "improvement", "trajectory"],
  Gauge: ["meter", "score", "level", "credit score", "assessment", "progress"],

  // Housing / shelter / utilities
  Home: ["housing", "shelter", "home", "residence", "apartment", "rent", "transitional housing", "sober living", "halfway house", "group home", "residential", "housing first", "permanent housing", "affordable housing", "section 8", "hud", "voucher", "subsidized housing", "public housing"],
  Hotel: ["housing", "shelter", "hotel", "motel", "lodging", "transitional", "temporary housing", "emergency shelter", "overnight"],
  Bed: ["housing", "shelter", "bed", "sleep", "overnight", "transitional housing", "emergency shelter"],
  BedDouble: ["housing", "shelter", "bedroom", "lodging", "shared housing"],
  Tent: ["housing", "shelter", "camp", "tent", "homeless", "outdoor", "unsheltered", "encampment", "homelessness"],
  Lamp: ["light", "lamp", "utilities", "utility assistance", "liheap", "energy assistance"],
  Plug: ["electricity", "outlet", "utilities", "power", "utility assistance", "liheap", "electric bill"],
  Battery: ["battery", "power", "energy", "utilities"],
  Fuel: ["gas", "fuel", "energy", "heating", "utility", "liheap"],
  Cloud: ["cloud", "weather", "storage", "online"],
  CloudRain: ["rain", "weather", "inclement weather"],
  Snowflake: ["winter", "cold", "snow", "weatherization", "heating assistance"],
  Wind: ["wind", "air", "weather"],
  Waves: ["water", "wave", "ocean", "water bill", "utilities"],
  Droplet: ["water", "hydration", "water utility", "drinking water"],
  Recycle: ["recycle", "environment", "green", "eco", "sustainability", "community"],

  // Food / nutrition
  Utensils: ["food", "meal", "eat", "dining", "nutrition", "kitchen", "food bank", "food pantry", "soup kitchen", "hunger", "food insecurity", "free meals", "congregate meals"],
  UtensilsCrossed: ["food", "restaurant", "dining", "meal", "nutrition", "food service", "catering"],
  Soup: ["food", "soup", "kitchen", "meal", "nutrition", "shelter", "soup kitchen", "hot meal", "community meal", "food bank"],
  Apple: ["food", "fruit", "produce", "apple", "nutrition", "healthy", "healthy eating", "snap", "ebt"],
  Banana: ["food", "fruit", "produce", "banana", "nutrition", "healthy"],
  Carrot: ["food", "vegetable", "produce", "carrot", "nutrition", "healthy food"],
  Cherry: ["food", "fruit", "produce", "cherry"],
  Grape: ["food", "fruit", "produce", "grape"],
  Salad: ["food", "salad", "healthy", "nutrition", "vegetables", "produce", "fruit"],
  Sandwich: ["food", "sandwich", "lunch", "meal", "nutrition", "brown bag", "box lunch"],
  Pizza: ["food", "pizza", "meal", "nutrition"],
  Egg: ["food", "egg", "breakfast", "protein", "nutrition"],
  Beef: ["food", "meat", "beef", "protein", "nutrition"],
  Drumstick: ["food", "chicken", "meat", "protein", "nutrition"],
  Fish: ["food", "fish", "seafood", "protein", "nutrition"],
  Milk: ["food", "milk", "dairy", "wic", "nutrition"],
  Cookie: ["food", "cookie", "snack", "dessert"],
  Donut: ["food", "donut", "snack", "dessert"],
  Croissant: ["food", "bakery", "bread", "breakfast"],
  IceCream: ["food", "icecream", "dessert", "treat"],
  Candy: ["food", "candy", "sweet", "treat"],
  Coffee: ["food", "coffee", "drink", "beverage", "cafe", "break", "morning", "social"],
  CupSoda: ["food", "drink", "beverage", "soda", "hydration"],
  Vegan: ["food", "vegan", "plant based", "vegetarian", "diet", "nutrition", "produce"],
  Popcorn: ["food", "popcorn", "snack", "movie", "recreation"],

  // Transportation
  Car: ["car", "drive", "vehicle", "auto", "license", "transportation", "transit", "mobility", "driver license", "license reinstatement", "driving record", "dui", "auto insurance", "vehicle registration", "rideshare"],
  Bus: ["bus", "transit", "transportation", "public transit", "bus pass", "metro", "public transportation", "mobility", "commute"],
  Train: ["train", "transit", "transportation", "rail", "commuter rail", "light rail", "commute", "mobility"],
  TrainFront: ["train", "transit", "transportation", "rail", "commuter", "subway", "commute", "mobility"],
  Bike: ["bike", "cycling", "bicycle", "transportation", "transit", "mobility", "active transportation", "commute"],
  Plane: ["plane", "flight", "airplane", "travel", "air travel", "transportation", "transit"],
  Ship: ["ship", "boat", "marine", "water transport", "transportation"],
  Map: ["map", "directions", "navigate", "navigation", "location", "address", "find", "resource map", "area map", "service map"],
  MapPin: ["map", "location", "place", "address", "site", "service location", "office location", "navigate", "pin", "find us"],
  Navigation: ["map", "navigation", "directions", "gps", "get there", "wayfinding", "location", "navigate"],
  Compass: ["map", "guidance", "direction", "navigate", "navigation", "explore", "orientation", "career compass", "life direction", "find your way"],
  Route: ["map", "route", "path", "directions", "navigate", "navigation", "roadmap", "plan", "steps", "journey", "get there"],
  TrafficCone: ["construction", "roadwork", "caution", "in progress", "detour"],
  Footprints: ["map", "walking", "steps", "journey", "path", "progress", "milestones", "recovery journey", "route", "navigate"],

  // Tech / digital literacy
  Computer: ["computer", "pc", "tech", "desktop", "digital skills"],
  Laptop: ["laptop", "computer", "digital", "online", "device", "digital literacy", "technology", "distance learning", "telehealth"],
  Smartphone: ["phone", "mobile", "smartphone", "device", "app", "digital", "cell phone", "mobile access", "text"],
  Monitor: ["monitor", "screen", "computer", "display", "workstation"],
  Keyboard: ["keyboard", "typing", "computer", "keyboarding", "typing skills"],
  Code: ["coding", "developer", "software", "programming", "tech skills", "web development", "bootcamp"],
  Cpu: ["tech", "hardware", "ai", "artificial intelligence", "technology"],
  Database: ["data", "database", "records", "information system", "case management system"],
  Network: ["network", "connect", "internet", "social network", "community network", "connectivity"],
  Wifi: ["wifi", "internet", "connectivity", "broadband", "internet access", "digital divide", "free wifi"],
  Signal: ["signal", "service", "connectivity", "cell service", "mobile data"],
  Webcam: ["webcam", "video", "telehealth", "virtual", "video call", "remote", "zoom"],
  Terminal: ["terminal", "developer", "command", "tech", "coding"],

  // Communication
  Phone: ["phone", "call", "contact", "hotline", "helpline", "phone access", "calling", "landline"],
  PhoneCall: ["call", "contact", "ring", "reach out", "call for help", "hotline"],
  Mail: ["mail", "email", "post", "correspondence", "letter", "postal mail", "mailing"],
  MessageCircle: ["chat", "message", "talk", "conversation", "peer chat", "text"],
  MessageSquare: ["message", "chat", "sms", "text message", "texting", "outreach"],
  Inbox: ["inbox", "messages", "correspondence", "incoming"],
  Send: ["send", "submit", "outgoing", "apply", "submit application"],
  Bell: ["notification", "alert", "bell", "reminder", "alarm", "appointment reminder"],
  Megaphone: ["advocacy", "announce", "voice", "outreach", "campaign", "awareness", "public speaking", "community organizing", "activism"],
  Mic: ["mic", "podcast", "speaking", "voice", "interview", "public speaking", "storytelling", "testimony"],
  Headphones: ["audio", "music", "podcast", "listen", "audio content", "headphones"],
  Headset: ["headset", "support", "callcenter", "customer service", "virtual support"],
  Speaker: ["speaker", "audio", "sound", "public address", "announcement"],
  Volume2: ["audio", "volume", "sound", "accessibility", "hearing"],
  Podcast: ["podcast", "audio", "show", "episode", "listen"],
  Radio: ["radio", "broadcast", "audio", "community radio"],
  Tv: ["tv", "media", "watch", "video content", "educational video"],
  Video: ["video", "film", "media", "instructional video", "documentary"],
  Film: ["film", "movie", "cinema", "video production", "documentary"],
  Newspaper: ["news", "press", "media", "article", "newsletter", "publication", "announcement"],
  Contact: ["contact", "directory", "person", "contact list", "resource directory"],
  LinkIcon: ["link", "url", "share", "resource link", "website", "referral"],

  // Faith / spiritual
  Church: ["faith", "church", "religion", "spiritual", "ministry", "worship", "chaplain", "pastor", "congregation", "faith based", "pray", "prayer", "bible", "mosque", "temple", "synagogue", "spirituality"],

  // Recreation / hobbies / arts
  Music: ["music", "song", "art", "music therapy", "musical instrument", "choir", "band"],
  Drum: ["drum", "music", "drumming", "percussion", "rhythm"],
  Drama: ["drama", "theater", "acting", "performing arts", "expression"],
  Gamepad2: ["game", "gaming", "play", "recreation", "leisure", "activity"],
  Joystick: ["game", "play", "arcade", "recreation"],
  Camera: ["photo", "camera", "photography", "art", "media", "documentary", "journalism"],
  ImageIcon: ["image", "photo", "gallery", "visual arts", "media"],
  Image: ["image", "photo", "gallery", "visual arts"],
  Dumbbell: ["fitness", "gym", "exercise", "workout", "strength", "physical", "health", "recreation", "physical fitness", "sport"],
  Volleyball: ["sport", "ball", "recreation", "team sport", "athletics", "physical activity"],
  Trophy: ["trophy", "win", "achievement", "success", "milestone", "goal reached", "accomplishment"],
  Medal: ["medal", "honor", "veteran", "achievement", "award", "recognition"],
  Award: ["award", "achievement", "honor", "recognition", "certificate", "accolade", "distinction"],
  Ribbon: ["ribbon", "awareness", "cause", "campaign", "month", "awareness month"],
  FerrisWheel: ["amusement", "fun", "park", "recreation", "leisure", "family activity"],
  Mountain: ["challenge", "mountain", "outdoor", "adventure", "overcoming", "perseverance", "resilience"],
  MountainSnow: ["mountain", "winter", "outdoor", "adventure"],
  TreePine: ["tree", "nature", "forest", "outdoor", "environment", "green space"],
  TreeDeciduous: ["tree", "nature", "forest", "outdoor", "green"],
  Leaf: ["nature", "green", "eco", "growth", "plant", "healing", "natural", "environment"],
  Flower: ["flower", "garden", "nature", "beauty", "bloom", "growth"],
  Flower2: ["garden", "flower", "bloom", "horticulture", "gardening"],
  Bird: ["animal", "pet", "bird", "wildlife", "freedom", "release", "liberation", "soar", "hope", "nature"],
  Dog: ["animal", "pet", "dog", "service animal", "animal assisted", "therapy dog", "companionship"],
  Cat: ["animal", "pet", "cat", "companionship", "therapy animal"],
  PawPrint: ["animal", "pet", "paw", "dog", "cat", "animal assisted therapy", "service animal"],

  // Veterans / military
  Flag: ["veteran", "military", "country", "patriot", "goal", "vets", "armed forces", "service member", "military family", "deployment", "va", "veterans affairs"],
  Swords: ["military", "veteran", "combat", "armed forces", "service", "valor"],

  // Misc tools / time
  Clock: ["calendar", "schedule", "time", "hours", "appointment", "deadline", "time management", "punctuality"],
  AlarmClock: ["calendar", "schedule", "time", "alarm", "wake", "reminder", "morning", "routine"],
  CalendarDays: ["calendar", "schedule", "date", "time", "appointment", "planning", "time management", "scheduling"],
  CalendarCheck: ["calendar", "schedule", "time", "appointment", "confirmed", "check-in", "court date", "supervision", "meeting"],
  CalendarHeart: ["calendar", "schedule", "time", "event", "save the date", "love", "special day", "milestone"],
  Hourglass: ["calendar", "schedule", "time", "wait", "patience", "deadline", "countdown", "pending"],
  Timer: ["calendar", "schedule", "time", "timer", "duration", "countdown", "timed"],
  History: ["history", "past", "record", "criminal history", "background", "prior", "previous"],
  Ticket: ["ticket", "event", "voucher", "bus ticket", "transportation voucher", "admission"],
  Tag: ["tag", "label", "category", "type", "classification"],
  Search: ["search", "find", "lookup", "locate", "resource finder", "service finder"],
  Settings: ["settings", "config", "preferences", "options", "manage"],
  Layers: ["layers", "stack", "categories", "multiple", "levels", "tiers"],
  Boxes: ["inventory", "boxes", "supplies", "goods", "materials", "resource kit", "hygiene kit"],
  Package: ["package", "delivery", "supplies", "care package", "kit", "bundle"],
  Magnet: ["attract", "magnet", "engagement", "draw", "pull"],
  Anchor: ["stability", "anchor", "ground", "marine", "foundation", "roots", "grounding", "stability"],
  Crown: ["leadership", "premium", "royal", "excellence", "elite", "top", "lead"],
  Gem: ["gem", "premium", "value", "treasure", "hidden gem", "asset"],
  Gift: ["gift", "donation", "giving", "charity", "donation", "in-kind", "contribution", "free"],
  Globe: ["world", "global", "travel", "international", "earth", "community", "worldwide", "diverse"],
  Rocket: ["launch", "startup", "growth", "boost", "momentum", "accelerate", "fast track", "launch pad"],
  Star: ["star", "favorite", "top", "featured", "excellence", "aspiration", "highlighted"],
  ThumbsUp: ["approve", "like", "positive", "helpful", "endorsed", "recommended"],
  Target: ["goal", "target", "objective", "focus", "aim", "goal setting", "outcomes", "milestone"],
  Puzzle: ["puzzle", "problem", "solution", "fit", "piece", "comprehensive", "holistic"],
  Feather: ["light", "feather", "writing", "gentle", "mindfulness"],
  Flame: ["fire", "passion", "energy", "motivation", "drive", "recovery", "sobriety", "burning desire"],
  Zap: ["energy", "power", "fast", "spark", "electric", "quick", "rapid", "boost", "instant"],
  Flashlight: ["light", "find", "guide", "illuminate", "clarity", "discovery"],
  Watch: ["time", "watch", "schedule", "timing", "management"],
  Weight: ["weight", "fitness", "scale", "balance", "physical health"],
  Printer: ["print", "document", "office", "printing", "copy", "fax"],
  Backpack: ["youth", "student", "school", "kid", "outdoor", "young adult", "teen", "juvenile", "youth services"],
  Bookmark: ["bookmark", "save", "favorite", "resource", "reference", "handy"],
  CircleDot: ["focus", "point", "specific", "targeted", "precise"],
  CircleHelp: ["help", "question", "faq", "how to", "guidance", "assistance", "support"],
  Info: ["info", "information", "about", "details", "overview", "learn more", "fact sheet"],
  Infinity: ["infinite", "unlimited", "ongoing", "continuous", "lifelong", "long-term"],
  ShoppingBag: ["shop", "retail", "shopping", "purchase", "goods", "supplies", "clothing assistance"],
  ShoppingBasket: ["basket", "groceries", "shopping", "food", "grocery", "pantry"],
  ShoppingCart: ["cart", "checkout", "shopping", "grocery", "online shopping"],
  Store: ["store", "shop", "market", "thrift", "resale", "social enterprise", "commissary"],
  Microwave: ["kitchen", "appliance", "cooking", "food prep"],
  Armchair: ["furniture", "rest", "comfort", "waiting room", "lounge", "relaxation"],
  Umbrella: ["protection", "rain", "cover", "safety net", "insurance", "covered", "assistance"],
};

// Score an icon against a category title. Whole-word matches score higher
// than substring matches so "car" in "care" doesn't beat "car" as a word.
// Bonus when the icon name itself appears in the title.
function scoreIconForTitle(iconName: string, title: string): number {
  const kws = ICON_KEYWORDS[iconName];
  if (!kws) return 0;
  const t = title.toLowerCase();
  const tokens = t.split(/[^a-z0-9]+/).filter(Boolean);
  let score = 0;
  for (const kw of kws) {
    const k = kw.toLowerCase();
    if (tokens.includes(k)) score += 10;
    else if (t.includes(k)) score += 5;
  }
  if (t.includes(iconName.toLowerCase())) score += 3;
  return score;
}

/**
 * Pick a single icon name relevant to `title`, optionally excluding one icon
 * (typically the current one). Falls back to a random icon when no keywords match.
 */
export function pickRelevantIcon(opts: {
  title?: string | null;
  exclude?: string | null;
}): string {
  const title = (opts.title ?? "").trim();
  const exclude = opts.exclude ?? null;
  const names = Object.keys(ICON_REGISTRY).filter((n) => n !== exclude);
  const rand = <T,>(arr: T[]) => arr[Math.floor(Math.random() * arr.length)];
  if (!title) return rand(names);
  const scored = names
    .map((n) => ({ n, s: scoreIconForTitle(n, title) }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s);
  if (scored.length) {
    // When multiple icons tie, pick randomly among them so regenerating
    // produces variety rather than always returning the same icon.
    const top = scored[0].s;
    const tied = scored.filter((x) => x.s === top).map((x) => x.n);
    return rand(tied);
  }
  return rand(names);
}

/**
 * Pick an icon name + color that don't collide with anything already in use.
 * If a title is provided, prefer icons whose keywords match the title.
 */
export function generateUniqueCategoryIcon(opts: {
  usedNames: Iterable<string | null | undefined>;
  usedColors: Iterable<string | null | undefined>;
  title?: string | null;
}): { icon_name: string; icon_color: string } {
  const usedN = new Set(Array.from(opts.usedNames).filter(Boolean) as string[]);
  const usedC = new Set(Array.from(opts.usedColors).filter(Boolean) as string[]);

  const names = Object.keys(ICON_REGISTRY);
  const availNames = names.filter((n) => !usedN.has(n));
  const availColors = COLOR_POOL.filter((c) => !usedC.has(c));

  const namePool = availNames.length ? availNames : names;
  const colorPool = availColors.length ? availColors : COLOR_POOL;

  const rand = <T,>(arr: T[]) => arr[Math.floor(Math.random() * arr.length)];

  let chosenName: string;
  const title = (opts.title ?? "").trim();
  if (title) {
    const scored = namePool
      .map((n) => ({ n, s: scoreIconForTitle(n, title) }))
      .filter((x) => x.s > 0)
      .sort((a, b) => b.s - a.s);
    if (scored.length) {
      const top = scored[0].s;
      const tied = scored.filter((x) => x.s === top).map((x) => x.n);
      chosenName = rand(tied);
    } else {
      chosenName = rand(namePool);
    }
  } else {
    chosenName = rand(namePool);
  }

  return {
    icon_name: chosenName,
    icon_color: rand(colorPool),
  };
}
