import {
  Activity,
  AlarmClock,
  AlertOctagon,
  AlertTriangle,
  Ambulance,
  Anchor,
  Apple,
  Archive,
  Armchair,
  Award,
  Axe,
  Baby,
  Backpack,
  BadgeCheck,
  Banana,
  Bandage,
  BarChart3,
  Bath,
  Battery,
  Beaker,
  Bed,
  BedDouble,
  Beef,
  Beer,
  Bell,
  Bike,
  Bird,
  Bone,
  Book,
  BookA,
  BookHeart,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Bookmark,
  Boxes,
  Brain,
  Briefcase,
  Brush,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  CalendarCheck,
  CalendarDays,
  CalendarHeart,
  Camera,
  Candy,
  Car,
  Carrot,
  Cat,
  ChefHat,
  Cherry,
  Church,
  CircleDollarSign,
  CircleDot,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudRain,
  Clover,
  Code,
  Coffee,
  Compass,
  Computer,
  Construction,
  Contact,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  Crown,
  CupSoda,
  Database,
  Dog,
  DollarSign,
  Donut,
  Drama,
  Droplet,
  Drum,
  Drumstick,
  Dumbbell,
  Ear,
  Egg,
  Factory,
  Feather,
  FerrisWheel,
  FileBadge,
  FileCheck,
  FileText,
  Film,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  Flashlight,
  Flower,
  Flower2,
  Folder,
  Footprints,
  Forklift,
  Fuel,
  Gamepad2,
  Gauge,
  Gavel,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Grape,
  Hammer,
  HandCoins,
  HandHeart,
  HandHelping,
  Handshake,
  HardHat,
  Headphones,
  Headset,
  Heart,
  HeartHandshake,
  HeartPulse,
  History,
  Home,
  Hospital,
  Hotel,
  Hourglass,
  IceCream,
  IdCard,
  Image as ImageIcon,
  Inbox,
  Infinity,
  Info,
  Joystick,
  Key,
  KeyRound,
  Keyboard,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Link as LinkIcon,
  Lock,
  Magnet,
  Mail,
  Map,
  MapPin,
  Martini,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  Microscope,
  Microwave,
  Milk,
  Monitor,
  Moon,
  Mountain,
  MountainSnow,
  Music,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  Package,
  Palette,
  Paintbrush,
  PartyPopper,
  PawPrint,
  Pen,
  PenTool,
  Pencil,
  Phone,
  PhoneCall,
  PiggyBank,
  Pill,
  PillBottle,
  Pizza,
  Plane,
  Plug,
  Podcast,
  Popcorn,
  Printer,
  Puzzle,
  Radio,
  Rainbow,
  Receipt,
  Recycle,
  RefreshCw,
  Ribbon,
  Rocket,
  Route,
  Ruler,
  Salad,
  Sandwich,
  Scale,
  School,
  Scissors,
  ScrollText,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Signal,
  Siren,
  Smartphone,
  Smile,
  Snowflake,
  Soup,
  Sparkles,
  Speaker,
  Sprout,
  Stamp,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Swords,
  Syringe,
  Tag,
  Target,
  Telescope,
  Tent,
  Terminal,
  ThumbsUp,
  Ticket,
  Timer,
  Tractor,
  TrafficCone,
  Train,
  TrainFront,
  TreeDeciduous,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Unlock,
  UserCheck,
  UserPlus,
  Users,
  Utensils,
  UtensilsCrossed,
  Vegan,
  Video,
  Volleyball,
  Volume2,
  Vote,
  Wallet,
  Wand,
  Watch,
  Waves,
  Webcam,
  Weight,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICON_REGISTRY: Record<string, LucideIcon> = {
  Activity, AlarmClock, AlertOctagon, AlertTriangle, Ambulance, Anchor, Apple, Archive, Armchair,
  Award, Axe, Baby, Backpack, BadgeCheck, Banana, Bandage, BarChart3, Bath, Battery,
  Beaker, Bed, BedDouble, Beef, Beer, Bell, Bike, Bird, Bone, Book, BookA, BookHeart,
  BookMarked, BookOpen, BookOpenCheck, Bookmark, Boxes, Brain, Briefcase, Brush,
  Building, Building2, Bus, Cake, Calculator, CalendarCheck, CalendarDays,
  CalendarHeart, Camera, Candy, Car, Carrot, Cat, ChefHat, Cherry, Church,
  CircleDollarSign, CircleDot, CircleHelp, ClipboardCheck, ClipboardList, Clock,
  Cloud, CloudRain, Clover, Code, Coffee, Compass, Computer, Construction, Contact,
  Cookie, Cpu, CreditCard, Croissant, Crown, CupSoda, Database, Dog, DollarSign,
  Donut, Drama, Droplet, Drum, Drumstick, Dumbbell, Ear, Egg, Factory, Feather,
  FerrisWheel, FileBadge, FileCheck, FileText, Film, Fingerprint, Fish, Flag, Flame,
  Flashlight, Flower, Flower2, Folder, Footprints, Forklift, Fuel, Gamepad2, Gauge,
  Gavel, Gem, Gift, Glasses, Globe, GraduationCap, Grape, Hammer, HandCoins,
  HandHeart, HandHelping, Handshake, HardHat, Headphones, Headset, Heart,
  HeartHandshake, HeartPulse, History, Home, Hospital, Hotel, Hourglass, IceCream,
  IdCard, Image: ImageIcon, Inbox, Infinity, Info, Joystick, Key, KeyRound, Keyboard,
  Lamp, Landmark, Languages, Laptop, Layers, Leaf, Library, LifeBuoy, Lightbulb,
  LineChart, Link: LinkIcon, Lock, Magnet, Mail, Map, MapPin, Martini, Medal,
  Megaphone, MessageCircle, MessageSquare, Mic, Microscope, Microwave, Milk, Monitor,
  Moon, Mountain, MountainSnow, Music, Navigation, Network, Newspaper, Notebook,
  NotebookPen, Package, Palette, Paintbrush, PartyPopper, PawPrint, Pen, PenTool,
  Pencil, Phone, PhoneCall, PiggyBank, Pill, PillBottle, Pizza, Plane, Plug, Podcast,
  Popcorn, Printer, Puzzle, Radio, Rainbow, Receipt, Recycle, RefreshCw, Ribbon,
  Rocket, Route, Ruler, Salad, Sandwich, Scale, School, Scissors, ScrollText, Search,
  Send, Settings, Shield, ShieldCheck, Ship, Shirt, ShoppingBag, ShoppingBasket,
  ShoppingCart, Shovel, ShowerHead, Signal, Siren, Smartphone, Smile, Snowflake, Soup, Sparkles,
  Speaker, Sprout, Stamp, Star, Stethoscope, Store, Sun, Sunrise, Sunset, Swords,
  Syringe, Tag, Target, Telescope, Tent, Terminal, ThumbsUp, Ticket, Timer, Tractor,
  TrafficCone, Train, TrainFront, TreeDeciduous, TreePine, Trophy, Truck, Tv,
  Umbrella, Unlock, UserCheck, UserPlus, Users, Utensils, UtensilsCrossed, Vegan, Video,
  Volleyball, Volume2, Vote, Wallet, Wand, Watch, Waves, Webcam, Weight, Wheat, Wifi,
  Wind, Wine, Wrench, Zap,
};

// Curated palette of distinct, accessible oklch colors for category icons.
export const COLOR_POOL: string[] = [
  "oklch(0.45 0.09 165)", "oklch(0.45 0.10 280)", "oklch(0.48 0.08 210)",
  "oklch(0.45 0.04 250)", "oklch(0.45 0.10 330)", "oklch(0.52 0.10 85)",
  "oklch(0.48 0.09 145)", "oklch(0.50 0.11 15)",  "oklch(0.50 0.10 70)",
  "oklch(0.50 0.10 40)",  "oklch(0.48 0.08 110)", "oklch(0.42 0.10 20)",
  "oklch(0.48 0.10 305)", "oklch(0.42 0.07 200)", "oklch(0.40 0.08 155)",
  "oklch(0.46 0.08 195)", "oklch(0.48 0.06 140)", "oklch(0.45 0.07 240)",
  "oklch(0.45 0.04 70)",  "oklch(0.55 0.11 90)",  "oklch(0.50 0.12 5)",
  "oklch(0.46 0.11 55)",  "oklch(0.50 0.10 100)", "oklch(0.46 0.10 130)",
  "oklch(0.44 0.10 175)", "oklch(0.46 0.10 220)", "oklch(0.44 0.11 260)",
  "oklch(0.46 0.12 295)", "oklch(0.48 0.11 320)", "oklch(0.50 0.10 350)",
  "oklch(0.42 0.06 30)",  "oklch(0.42 0.06 180)", "oklch(0.55 0.09 60)",
  "oklch(0.40 0.08 270)", "oklch(0.52 0.08 170)", "oklch(0.48 0.10 25)",
  "oklch(0.46 0.09 245)", "oklch(0.50 0.10 125)", "oklch(0.44 0.09 95)",
  "oklch(0.48 0.10 285)",
];

export function resolveCategoryIcon(name: string | null | undefined): LucideIcon {
  if (name && ICON_REGISTRY[name]) return ICON_REGISTRY[name];
  return Sparkles;
}

// Keywords mapped to icons. Case-insensitive substring/word matches against the title.
const ICON_KEYWORDS: Record<string, string[]> = {
  // Recovery / mental / wellness
  RefreshCw: ["reentry", "re-entry", "restart", "renew", "reset", "transition", "return"],
  Brain: ["mind", "mental", "brain", "cognitive", "psych", "therapy", "counseling", "neuro"],
  HeartPulse: ["health", "vital", "wellness", "pulse", "cardio"],
  Heart: ["love", "care", "compassion", "relationship", "wellness"],
  HeartHandshake: ["support", "compassion", "care", "ally"],
  HandHeart: ["care", "giving", "donate", "compassion", "volunteer"],
  HandHelping: ["help", "assist", "support", "aid", "outreach"],
  Handshake: ["partner", "mentor", "agreement", "deal", "ally"],
  LifeBuoy: ["help", "rescue", "crisis", "emergency", "support", "hotline"],
  Smile: ["happy", "joy", "positive", "smile", "wellness"],
  Sparkles: ["wellness", "inspire", "magic", "shine", "spark"],
  Sprout: ["growth", "new", "start", "seed", "grow"],
  Sun: ["sun", "energy", "bright", "solar", "morning"],
  Sunrise: ["morning", "rise", "new", "dawn"],
  Sunset: ["evening", "calm", "rest"],
  Moon: ["night", "sleep", "rest", "moon"],
  Bath: ["selfcare", "bath", "relax"],
  ShowerHead: ["shower", "hygiene", "clean"],
  Wand: ["magic", "transform"],
  Clover: ["luck", "fortune", "lucky"],
  Rainbow: ["pride", "lgbt", "lgbtq", "diversity", "rainbow"],

  // Substance / addiction
  Wine: ["alcohol", "wine", "sobriety", "addiction", "recovery", "aa"],
  Beer: ["alcohol", "beer", "drinking"],
  Martini: ["alcohol", "bar", "drinks"],
  Pill: ["drug", "medication", "pill", "rx", "narcotic"],
  PillBottle: ["medication", "prescription", "pharmacy", "drug"],
  Syringe: ["needle", "injection", "drug", "harm reduction", "vaccine"],

  // Medical / healthcare
  Stethoscope: ["doctor", "medical", "clinic", "checkup", "primary care"],
  Hospital: ["hospital", "medical", "clinic", "healthcare", "emergency room"],
  Ambulance: ["emergency", "ambulance", "ems", "911"],
  Bandage: ["injury", "first aid", "wound"],
  Microscope: ["lab", "research", "science"],
  Beaker: ["lab", "science", "test", "research"],
  Bone: ["bone", "ortho", "skeleton"],
  Ear: ["hearing", "ear", "audio", "listen"],
  Glasses: ["vision", "eye", "glasses", "optometry"],
  Activity: ["activity", "vital", "monitor", "pulse"],

  // Family / kids
  Baby: ["baby", "infant", "newborn", "parent"],
  Users: ["community", "group", "team", "peer", "people", "social"],
  UserCheck: ["verified", "approved", "member"],
  UserPlus: ["enroll", "register", "join", "signup", "intake"],
  PartyPopper: ["celebration", "party", "event"],
  Cake: ["birthday", "celebration", "party"],

  // Education / literacy
  GraduationCap: ["education", "graduate", "degree", "college", "university", "academic", "ged"],
  School: ["school", "class", "education", "training", "k12"],
  BookOpen: ["read", "book", "study", "literacy", "guide"],
  BookOpenCheck: ["learning", "study", "curriculum"],
  Book: ["book", "read", "study"],
  BookA: ["language", "dictionary", "vocabulary", "spanish", "english", "esl"],
  BookMarked: ["bookmark", "saved", "study"],
  BookHeart: ["story", "favorite", "memoir"],
  Library: ["library", "resource", "archive", "collection"],
  Pencil: ["write", "edit", "homework", "note"],
  Pen: ["write", "sign", "compose"],
  PenTool: ["design", "draw", "create"],
  Paintbrush: ["art", "paint", "creative"],
  Brush: ["art", "paint", "brush"],
  Palette: ["art", "creative", "design", "color"],
  Notebook: ["note", "journal", "study"],
  NotebookPen: ["journal", "note", "write"],
  ScrollText: ["scroll", "document", "history"],
  Languages: ["language", "translate", "bilingual", "interpreter"],
  Lightbulb: ["idea", "tip", "insight", "innovation", "learn"],
  Telescope: ["explore", "discover", "vision"],
  Ruler: ["measure", "ruler", "math"],
  Calculator: ["math", "calc", "tax", "accounting", "number"],
  Sigma: ["math", "sum", "statistics"],

  // Work / employment / trades
  Briefcase: ["job", "career", "work", "employment", "business", "professional"],
  Building: ["office", "building", "company"],
  Building2: ["business", "office", "corporate", "organization"],
  Factory: ["factory", "manufacturing", "industrial", "warehouse"],
  HardHat: ["construction", "trade", "labor", "safety"],
  Hammer: ["construction", "trade", "build", "repair", "tool"],
  Wrench: ["repair", "tool", "fix", "maintenance", "mechanic"],
  Construction: ["construction", "build", "site"],
  Forklift: ["warehouse", "logistics", "forklift"],
  Shovel: ["dig", "labor", "landscape", "manual"],
  Axe: ["forestry", "lumber", "axe"],
  ChefHat: ["chef", "cook", "culinary", "food service", "kitchen"],
  Scissors: ["barber", "salon", "cosmetology", "hair", "cutting"],
  Shirt: ["clothing", "uniform", "apparel", "dress"],
  Truck: ["delivery", "trucking", "transport", "cdl", "logistics", "moving"],
  Tractor: ["farming", "agriculture", "tractor"],
  Wheat: ["farming", "agriculture", "grain"],

  // Documents / ID / paperwork
  FileText: ["document", "form", "record", "report", "paperwork"],
  FileCheck: ["verified", "approved", "complete"],
  FileBadge: ["certificate", "credential", "license"],
  ClipboardList: ["intake", "checklist", "task", "form"],
  ClipboardCheck: ["complete", "approved", "checklist"],
  IdCard: ["id", "identification", "license", "state id"],
  Stamp: ["stamp", "approve", "seal", "official"],
  BadgeCheck: ["verified", "certified", "credential"],
  Fingerprint: ["fingerprint", "background check", "biometric", "id"],
  Receipt: ["receipt", "bill", "invoice"],
  Folder: ["files", "folder", "documents"],
  Archive: ["archive", "storage", "records"],

  // Legal
  Scale: ["legal", "law", "justice", "rights", "attorney", "balance"],
  Gavel: ["court", "judge", "legal", "ruling", "sentence", "expungement"],
  Vote: ["vote", "voting", "election", "civic"],
  Landmark: ["government", "civic", "court", "capitol", "institution"],
  Lock: ["lock", "secure", "private"],
  KeyRound: ["access", "key", "unlock"],
  Key: ["access", "key", "unlock", "security"],
  Shield: ["safety", "security", "protect", "defense", "insurance"],
  ShieldCheck: ["protected", "secure", "verified"],
  Siren: ["emergency", "alert", "police", "911", "crisis", "hotline"],
  AlertOctagon: ["urgent", "stop", "danger", "warning", "alert"],
  AlertTriangle: ["warning", "alert", "caution", "risk"],
  Unlock: ["release", "freedom", "fresh start", "reentry", "open"],

  // Finance / money / benefits
  Wallet: ["wallet", "money", "budget", "finance"],
  PiggyBank: ["savings", "save", "budget"],
  CreditCard: ["credit", "card", "payment", "banking"],
  DollarSign: ["money", "cost", "price", "dollar"],
  CircleDollarSign: ["money", "finance", "cash"],
  HandCoins: ["benefits", "snap", "ebt", "assistance", "cash", "stipend"],
  Coins: ["coins", "money", "savings"],
  BarChart3: ["analytics", "stats", "report"],
  LineChart: ["trend", "growth", "analytics"],
  Gauge: ["meter", "score", "level"],

  // Housing / shelter / utilities
  Home: ["housing", "home", "shelter", "residence", "apartment", "rent"],
  Hotel: ["hotel", "motel", "lodging", "transitional"],
  Bed: ["bed", "sleep", "shelter"],
  BedDouble: ["bedroom", "shelter", "lodging"],
  Tent: ["camp", "tent", "homeless", "shelter", "outdoor"],
  Lamp: ["light", "lamp", "utilities"],
  Plug: ["electricity", "outlet", "utilities", "power"],
  Battery: ["battery", "power", "energy"],
  Fuel: ["gas", "fuel", "energy"],
  Cloud: ["cloud", "weather", "storage"],
  CloudRain: ["rain", "weather"],
  Snowflake: ["winter", "cold", "snow"],
  Wind: ["wind", "air", "weather"],
  Waves: ["water", "wave", "ocean"],
  Droplet: ["water", "hydration"],
  Recycle: ["recycle", "environment", "green", "eco"],

  // Food / nutrition
  Utensils: ["food", "meal", "eat", "dining", "nutrition", "kitchen"],
  UtensilsCrossed: ["restaurant", "dining", "meal"],
  Soup: ["soup", "kitchen", "meal", "shelter"],
  Apple: ["fruit", "apple", "nutrition", "healthy"],
  Banana: ["fruit", "banana"],
  Carrot: ["vegetable", "carrot", "produce"],
  Cherry: ["fruit", "cherry"],
  Grape: ["fruit", "grape"],
  Salad: ["salad", "healthy", "nutrition"],
  Sandwich: ["sandwich", "lunch", "meal"],
  Pizza: ["pizza", "food"],
  Egg: ["egg", "breakfast"],
  Beef: ["meat", "beef"],
  Drumstick: ["chicken", "meat", "food"],
  Fish: ["fish", "seafood"],
  Milk: ["milk", "dairy"],
  Cookie: ["cookie", "snack", "dessert"],
  Donut: ["donut", "snack", "dessert"],
  Croissant: ["bakery", "bread", "breakfast"],
  IceCream: ["icecream", "dessert"],
  Candy: ["candy", "sweet"],
  Coffee: ["coffee", "cafe", "break"],
  CupSoda: ["drink", "beverage", "soda"],
  Vegan: ["vegan", "plant based"],
  Popcorn: ["popcorn", "movie", "snack"],

  // Transportation
  Car: ["car", "drive", "vehicle", "auto", "license"],
  Bus: ["bus", "transit", "transportation", "public transit"],
  Train: ["train", "transit", "rail"],
  TrainFront: ["train", "transit", "rail"],
  Bike: ["bike", "cycling", "bicycle"],
  Plane: ["plane", "flight", "airplane", "travel"],
  Ship: ["ship", "boat", "marine"],
  Map: ["map", "directions", "navigate"],
  MapPin: ["location", "place", "address"],
  Navigation: ["navigation", "directions", "gps"],
  Compass: ["guidance", "direction", "navigate", "explore"],
  Route: ["route", "path", "directions"],
  TrafficCone: ["construction", "roadwork", "caution"],
  Footprints: ["walking", "steps", "journey", "path"],

  // Tech / digital literacy
  Computer: ["computer", "pc", "tech"],
  Laptop: ["laptop", "computer", "digital", "online", "device"],
  Smartphone: ["phone", "mobile", "smartphone", "device", "app", "digital"],
  Monitor: ["monitor", "screen", "computer"],
  Keyboard: ["keyboard", "typing", "computer"],
  Code: ["coding", "developer", "software", "programming"],
  Cpu: ["tech", "hardware", "ai"],
  Database: ["data", "database", "records"],
  Network: ["network", "connect", "internet"],
  Wifi: ["wifi", "internet", "connectivity"],
  Signal: ["signal", "service", "connectivity"],
  Webcam: ["webcam", "video", "telehealth"],
  Terminal: ["terminal", "developer", "command"],

  // Communication
  Phone: ["phone", "call", "contact", "hotline"],
  PhoneCall: ["call", "contact", "ring"],
  Mail: ["mail", "email", "post"],
  MessageCircle: ["chat", "message", "talk"],
  MessageSquare: ["message", "chat", "sms"],
  Inbox: ["inbox", "messages"],
  Send: ["send", "submit", "outgoing"],
  Bell: ["notification", "alert", "bell"],
  Megaphone: ["advocacy", "announce", "voice", "outreach", "campaign"],
  Mic: ["mic", "podcast", "speaking", "voice", "interview"],
  Headphones: ["audio", "music", "podcast", "listen"],
  Headset: ["headset", "support", "callcenter"],
  Speaker: ["speaker", "audio", "sound"],
  Volume2: ["audio", "volume", "sound"],
  Podcast: ["podcast", "audio", "show"],
  Radio: ["radio", "broadcast", "audio"],
  Tv: ["tv", "media", "watch"],
  Video: ["video", "film", "media"],
  Film: ["film", "movie", "cinema"],
  Newspaper: ["news", "press", "media", "article"],
  Contact: ["contact", "directory", "person"],
  LinkIcon: ["link", "url", "share"],

  // Faith / spiritual
  Church: ["faith", "church", "religion", "spiritual", "ministry", "worship", "chaplain"],

  // Recreation / hobbies / arts
  Music: ["music", "song", "art"],
  Drum: ["drum", "music"],
  Drama: ["drama", "theater", "acting"],
  Gamepad2: ["game", "gaming", "play", "recreation"],
  Joystick: ["game", "play", "arcade"],
  Camera: ["photo", "camera", "photography"],
  ImageIcon: ["image", "photo", "gallery"],
  Image: ["image", "photo", "gallery"],
  Dumbbell: ["fitness", "gym", "exercise", "workout", "strength", "physical"],
  Volleyball: ["sport", "ball", "recreation"],
  Trophy: ["trophy", "win", "achievement", "success"],
  Medal: ["medal", "honor", "veteran"],
  Award: ["award", "achievement", "honor", "recognition"],
  Ribbon: ["ribbon", "awareness", "cause"],
  FerrisWheel: ["amusement", "fun", "park"],
  Mountain: ["challenge", "mountain", "outdoor", "adventure"],
  MountainSnow: ["mountain", "winter", "outdoor"],
  TreePine: ["tree", "nature", "forest", "outdoor"],
  TreeDeciduous: ["tree", "nature", "forest"],
  Leaf: ["nature", "green", "eco", "growth", "plant"],
  Flower: ["flower", "garden", "nature"],
  Flower2: ["garden", "flower", "bloom"],
  Bird: ["bird", "freedom", "wildlife"],
  Dog: ["pet", "dog", "service animal"],
  Cat: ["pet", "cat", "animal"],
  PawPrint: ["pet", "animal", "paw"],

  // Veterans / military
  Flag: ["veteran", "military", "country", "patriot", "goal"],
  Swords: ["military", "veteran", "combat"],

  // Misc tools / time
  Clock: ["time", "schedule", "hours"],
  AlarmClock: ["alarm", "wake", "time"],
  CalendarDays: ["calendar", "schedule", "date"],
  CalendarCheck: ["appointment", "schedule", "confirmed"],
  CalendarHeart: ["event", "save the date", "love"],
  Hourglass: ["time", "wait", "patience"],
  Timer: ["timer", "duration", "time"],
  History: ["history", "past", "record"],
  Ticket: ["ticket", "event", "voucher"],
  Tag: ["tag", "label", "category"],
  Search: ["search", "find", "lookup"],
  Settings: ["settings", "config", "preferences"],
  Layers: ["layers", "stack", "categories"],
  Boxes: ["inventory", "boxes", "supplies"],
  Package: ["package", "delivery", "supplies"],
  Magnet: ["attract", "magnet"],
  Anchor: ["stability", "anchor", "ground", "marine"],
  Crown: ["leadership", "premium", "royal"],
  Gem: ["gem", "premium", "value"],
  Gift: ["gift", "donation", "giving", "charity"],
  Globe: ["world", "global", "travel", "international", "earth"],
  Rocket: ["launch", "startup", "growth", "boost"],
  Star: ["star", "favorite", "top", "featured"],
  ThumbsUp: ["approve", "like", "positive"],
  Target: ["goal", "target", "objective", "focus"],
  Puzzle: ["puzzle", "problem", "solution"],
  Feather: ["light", "feather", "writing"],
  Flame: ["fire", "passion", "energy"],
  Zap: ["energy", "power", "fast", "spark", "electric"],
  Flashlight: ["light", "find", "guide"],
  Watch: ["time", "watch"],
  Weight: ["weight", "fitness", "scale"],
  Printer: ["print", "document", "office"],
  Backpack: ["youth", "student", "school", "kid", "outdoor"],
  Bookmark: ["bookmark", "save", "favorite"],
  CircleDot: ["focus", "point"],
  CircleHelp: ["help", "question", "faq"],
  Info: ["info", "information", "about"],
  Infinity: ["infinite", "unlimited"],
  ShoppingBag: ["shop", "retail", "shopping"],
  ShoppingBasket: ["basket", "groceries", "shopping"],
  ShoppingCart: ["cart", "checkout", "shopping"],
  Store: ["store", "shop", "market"],
  Microwave: ["kitchen", "appliance"],
  Armchair: ["furniture", "rest", "comfort"],
  Umbrella: ["protection", "rain", "cover"],
};

function scoreIconForTitle(iconName: string, title: string): number {
  const kws = ICON_KEYWORDS[iconName];
  if (!kws) return 0;
  const t = title.toLowerCase();
  const tokens = t.split(/[^a-z0-9]+/).filter(Boolean);
  let score = 0;
  for (const kw of kws) {
    const k = kw.toLowerCase();
    if (tokens.includes(k)) score += 10;
    else if (t.includes(k)) score += 5;
  }
  if (t.includes(iconName.toLowerCase())) score += 3;
  return score;
}

/**
 * Pick an icon name + color that don't collide with anything already in use.
 * If a title is provided, prefer icons whose keywords match the title.
 */
export function generateUniqueCategoryIcon(opts: {
  usedNames: Iterable<string | null | undefined>;
  usedColors: Iterable<string | null | undefined>;
  title?: string | null;
}): { icon_name: string; icon_color: string } {
  const usedN = new Set(Array.from(opts.usedNames).filter(Boolean) as string[]);
  const usedC = new Set(Array.from(opts.usedColors).filter(Boolean) as string[]);

  const names = Object.keys(ICON_REGISTRY);
  const availNames = names.filter((n) => !usedN.has(n));
  const availColors = COLOR_POOL.filter((c) => !usedC.has(c));

  const namePool = availNames.length ? availNames : names;
  const colorPool = availColors.length ? availColors : COLOR_POOL;

  const rand = <T,>(arr: T[]) => arr[Math.floor(Math.random() * arr.length)];

  let chosenName: string;
  const title = (opts.title ?? "").trim();
  if (title) {
    const scored = namePool
      .map((n) => ({ n, s: scoreIconForTitle(n, title) }))
      .filter((x) => x.s > 0)
      .sort((a, b) => b.s - a.s);
    if (scored.length) {
      const top = scored[0].s;
      const tied = scored.filter((x) => x.s === top).map((x) => x.n);
      chosenName = rand(tied);
    } else {
      chosenName = rand(namePool);
    }
  } else {
    chosenName = rand(namePool);
  }

  return {
    icon_name: chosenName,
    icon_color: rand(colorPool),
  };
}
