export type TestPriority = "critical" | "high" | "medium" | "low";
export type TestStatus   = "untested" | "pass" | "fail" | "blocked" | "skipped";

export type QASection = {
  num: number;
  title: string;
};

export type QATest = {
  id: string;           // e.g. "1.1", "7.3"
  sectionNum: number;
  priority: TestPriority;
  title: string;
  description: string;
};

export const QA_SECTIONS: QASection[] = [
  { num:  1, title: "Sign-Up Flow" },
  { num:  2, title: "Sign-In Flow" },
  { num:  3, title: "Password Reset" },
  { num:  4, title: "Main Page & Public Experience" },
  { num:  5, title: "Category Page (User-Facing)" },
  { num:  6, title: "User Dashboard" },
  { num:  7, title: "Admin Access Control" },
  { num:  8, title: "Admin Content Management" },
  { num:  9, title: "Admin User Management" },
  { num: 10, title: "Admin Analytics" },
  { num: 11, title: "Admin Messages" },
  { num: 12, title: "Admin Facilities" },
  { num: 13, title: "Admin System Tools" },
  { num: 14, title: "Multilingual (EN / ES)" },
  { num: 15, title: "Analytics Data Integrity" },
  { num: 16, title: "Mobile & Responsive" },
  { num: 17, title: "Security & Edge Cases" },
  { num: 18, title: "Performance & Stability" },
];

export const QA_TESTS: QATest[] = [
  // ── Section 1 — Sign-Up Flow ──────────────────────────────────────────────
  { id: "1.1",  sectionNum: 1, priority: "critical", title: "Access gate (no facility URL)",
    description: "Navigate to /signup without a ?site= parameter. Verify no sign-up fields are shown and an error message says sign-up requires the facility device link. Sign-in should still be accessible." },
  { id: "1.2",  sectionNum: 1, priority: "critical", title: "Access gate (facility URL, no PIN)",
    description: "Navigate to /?site=validSiteId (no ?user= PIN). Open /signup. Verify sign-up is blocked with a 'no PIN' error. Sign-in should still work normally." },
  { id: "1.3",  sectionNum: 1, priority: "critical", title: "Access gate (PIN already registered)",
    description: "Navigate to /?site=validSiteId&user=PIN_WITH_ACCOUNT. Open /signup. Verify a 'PIN already registered' error appears and only the sign-in prompt is shown — no sign-up form." },
  { id: "1.4",  sectionNum: 1, priority: "medium", title: "Disclosure collapsed by default",
    description: "With a valid facility+PIN URL, open sign-up. Verify the consent disclosure is collapsed by default. Expand it. Verify it shows the full data collection explanation with links to Privacy Policy and Terms of Service." },
  { id: "1.5",  sectionNum: 1, priority: "high", title: "Create Account button disabled without checkbox",
    description: "Fill in all fields correctly but leave the acknowledgment checkbox unchecked. Verify the Create Account button is disabled or does nothing when clicked." },
  { id: "1.6",  sectionNum: 1, priority: "high", title: "Username validation",
    description: "Test: <3 chars → invalid; >32 chars → invalid; special chars (e.g. user@name) → invalid; valid format (john_doe_92) → availability check fires; already-taken username → 'That username is already taken' before submission." },
  { id: "1.7",  sectionNum: 1, priority: "low", title: "Password strength meter",
    description: "Enter passwords of varying complexity. Verify the 4-segment meter updates: <8 chars → Too short (1 red), 8+ lowercase only → Weak, mixed case + digits → Fair/Good, mixed case + digits + symbol → Strong." },
  { id: "1.8",  sectionNum: 1, priority: "high", title: "Password mismatch",
    description: "Enter a password and a different confirmation. Click Create Account. Verify an error toast appears and no account is created." },
  { id: "1.9",  sectionNum: 1, priority: "critical", title: "Math captcha must be answered correctly",
    description: "Enter an intentionally wrong answer to the math captcha (e.g., shown '4 + 7', enter 10). Click Create Account. Verify 'Captcha failed' appears and no account is created." },
  { id: "1.10", sectionNum: 1, priority: "medium", title: "Math captcha expires after 5 minutes",
    description: "Open the sign-up form, wait more than 5 minutes without submitting, then submit. Verify the captcha is rejected as expired and a new one is requested." },
  { id: "1.11", sectionNum: 1, priority: "medium", title: "Honeypot field is hidden",
    description: "Inspect the sign-up form HTML. Verify a hidden input field exists and is not visible to the user. (Do not fill it in — just verify its presence and invisibility.)" },
  { id: "1.12", sectionNum: 1, priority: "high", title: "Security questions required after sign-up",
    description: "Complete sign-up. Verify redirect to /dashboard?tab=account. Verify the Progress tab is locked with a prompt to set up security questions. Set up 2 questions. Verify the lock clears and content becomes accessible." },
  { id: "1.13", sectionNum: 1, priority: "high", title: "Must choose two different questions",
    description: "In the security questions form, try selecting the same question twice. Verify the second dropdown greys out the already-chosen question, preventing duplicates." },
  { id: "1.14", sectionNum: 1, priority: "high", title: "Successful sign-up redirects to account tab",
    description: "Complete a valid sign-up. Verify redirect to /dashboard?tab=account (not the home page) and the new profile is shown." },
  { id: "1.15", sectionNum: 1, priority: "medium", title: "Facility is pre-selected from URL",
    description: "Navigate to /?site=validSiteId&user=newPin. Open sign-up. Verify the facility is pre-selected and the user cannot change it to another facility." },
  { id: "1.16", sectionNum: 1, priority: "medium", title: "PIN is pre-filled and hidden",
    description: "Navigate via a facility URL with ?user=123456. Verify the inmate PIN field does not require manual entry — the PIN from session storage is submitted automatically." },

  // ── Section 2 — Sign-In Flow ─────────────────────────────────────────────
  { id: "2.1",  sectionNum: 2, priority: "critical", title: "Successful sign-in (correct facility + PIN)",
    description: "From /?site=correctSiteId&user=correctPin, sign in with valid credentials. Verify redirect to /dashboard." },
  { id: "2.2",  sectionNum: 2, priority: "critical", title: "Facility mismatch rejection",
    description: "Sign in as a Facility A user but from ?site=FacilityB_siteId. Verify the user is immediately signed out and shown a 'wrong link' error. Verify the user does not reach the dashboard." },
  { id: "2.3",  sectionNum: 2, priority: "critical", title: "PIN mismatch rejection",
    description: "Sign in as a Facility A user with the correct ?site= but ?user=WRONGPIN (a PIN belonging to a different user). Verify sign-in is rejected. Verify the user cannot access the dashboard." },
  { id: "2.4",  sectionNum: 2, priority: "critical", title: "Generic error for wrong password",
    description: "Enter a valid username but wrong password. Verify the error says 'Incorrect username or password' — not anything that reveals the username exists." },
  { id: "2.5",  sectionNum: 2, priority: "critical", title: "Generic error for nonexistent username",
    description: "Enter a username that does not exist. Verify the error is identical to the wrong-password error. Verify timing is similar (no measurable delay difference)." },
  { id: "2.6",  sectionNum: 2, priority: "high", title: "Admin/contributor bypass facility check",
    description: "Sign in as an admin from a facility URL (?site=...&user=...). Verify the admin is not subjected to the facility+PIN match check and is redirected to /admin normally." },
  { id: "2.7",  sectionNum: 2, priority: "high", title: "Facility User bypass facility check",
    description: "Sign in as a Facility User account from a facility URL. Verify the facility check does not block them and they are redirected to /admin." },
  { id: "2.8",  sectionNum: 2, priority: "medium", title: "Nav freeze during post-auth check",
    description: "Sign in on a shared-device URL. Observe the nav bar during the post-auth check. Verify it stays in its unauthenticated state (shows 'Sign In') until the check completes or fails." },
  { id: "2.9",  sectionNum: 2, priority: "critical", title: "Sign-out preserves facility + PIN URL",
    description: "From /?site=siteId&user=123456, sign in then sign out. Verify redirect back to /?site=siteId&user=123456 — not a bare /. Verify the next person must re-authenticate against that PIN." },
  { id: "2.10", sectionNum: 2, priority: "high", title: "Admin redirected to /admin after sign-in",
    description: "Sign in as an admin. Verify redirect goes to /admin, not /dashboard." },
  { id: "2.11", sectionNum: 2, priority: "high", title: "Contributor redirected to /admin after sign-in",
    description: "Sign in as a contributor. Verify redirect goes to /admin." },
  { id: "2.12", sectionNum: 2, priority: "high", title: "Redirect param is honored after sign-in",
    description: "Navigate to /admin/analytics while signed out. Verify redirect to /signup?redirect=/admin/analytics. Sign in as admin. Verify landing on /admin/analytics." },

  // ── Section 3 — Password Reset ────────────────────────────────────────────
  { id: "3.1",  sectionNum: 3, priority: "critical", title: "Username enumeration prevention at Step 1",
    description: "Enter a username that does not exist. Verify fake security question keys are returned and Step 2 appears as if a real user. Verify the error at Step 2 only says 'Username or security answers are incorrect.'" },
  { id: "3.2",  sectionNum: 3, priority: "critical", title: "Correct reset flow end-to-end",
    description: "Enter a valid username → verify correct 2 security questions → enter correct answers + new password → verify success toast → verify sign-in works with the new password." },
  { id: "3.3",  sectionNum: 3, priority: "critical", title: "Wrong answers are rejected",
    description: "Go through reset Step 1, then submit incorrect answers at Step 2. Verify a generic error appears and the password is not changed." },
  { id: "3.4",  sectionNum: 3, priority: "critical", title: "PIN + facility verification on shared device",
    description: "On ?site=A&user=PIN_belonging_to_UserX, initiate a reset for UserY's username. Verify the server returns fake questions — not UserY's real ones — because the PIN doesn't match." },
  { id: "3.5",  sectionNum: 3, priority: "critical", title: "Rate limiting — question probing (30/hour)",
    description: "Submit Step 1 (username lookup) 31 times from the same IP within one hour. Verify the 31st request returns a 'Too many requests' error." },
  { id: "3.6",  sectionNum: 3, priority: "critical", title: "Rate limiting — reset submissions (8/hour)",
    description: "Submit a full reset attempt 9 times from the same IP within one hour. Verify the 9th attempt is rejected with 'Too many requests.'" },
  { id: "3.7",  sectionNum: 3, priority: "high", title: "New password minimum length enforced",
    description: "At Step 2, enter a new password shorter than 8 characters. Verify the form prevents submission with an appropriate error." },
  { id: "3.8",  sectionNum: 3, priority: "high", title: "Password mismatch at reset",
    description: "Enter different values in 'New password' and 'Confirm password' at Step 2. Verify an error appears and the reset does not proceed." },

  // ── Section 4 — Main Page & Public Experience ─────────────────────────────
  { id: "4.1",  sectionNum: 4, priority: "high", title: "Category grid loads for anonymous visitor",
    description: "Visit the main page without signing in. Verify all published categories appear. Verify no progress bars appear on the cards." },
  { id: "4.2",  sectionNum: 4, priority: "high", title: "Progress bars appear when signed in",
    description: "Sign in as a user. Verify each category card shows a progress bar reflecting actual completion. Mark an item complete. Return to main page. Verify the bar updates." },
  { id: "4.3",  sectionNum: 4, priority: "high", title: "Categories / Items counter is accurate",
    description: "Verify the 'X Categories / Y Items' counter above the grid. Add a published category and item in admin. Refresh. Verify both numbers increase." },
  { id: "4.4",  sectionNum: 4, priority: "medium", title: "Item count respects facility restrictions",
    description: "Create an item in Category A restricted to Facility B. Sign in as Facility A user. Verify that item does not appear in the item count badge on Category A's card." },
  { id: "4.5",  sectionNum: 4, priority: "medium", title: "'New content' badge appears and clears",
    description: "Add a new item to a category. Sign in as a user who hasn't opened it. Verify a 'New content added' badge appears on the category card. Open the item. Return. Verify the badge is gone." },
  { id: "4.6",  sectionNum: 4, priority: "high", title: "Search returns correct results",
    description: "Type 2+ characters in search. Verify results contain only items with matching title/description. Verify facility-restricted items are hidden. Clear search — verify grid returns." },
  { id: "4.7",  sectionNum: 4, priority: "medium", title: "Search with no results shows empty state",
    description: "Search for a string with no matches. Verify 'No results found' message appears. Verify the category grid is not shown alongside the message." },
  { id: "4.8",  sectionNum: 4, priority: "high", title: "Site-wide message banner shows and dismisses",
    description: "Enable the site-wide message in admin. Sign in as a user. Verify the banner appears. Dismiss it. Reload — verify it's gone. Update the message in admin. Reload — verify the banner reappears." },
  { id: "4.9",  sectionNum: 4, priority: "high", title: "Facility message shows for the right facility only",
    description: "Set a message for Facility A. Sign in as Facility A user — verify the banner appears. Sign in as Facility B user — verify the banner does not appear." },
  { id: "4.10", sectionNum: 4, priority: "medium", title: "Anonymous facility message (via URL)",
    description: "Without signing in, visit /?site=facilityASiteId. Verify the Facility A message banner appears." },
  { id: "4.11", sectionNum: 4, priority: "high", title: "Language toggle on main page",
    description: "Click EN/ES toggle. Verify all nav labels, category names (if translated), taglines, and UI text switch to Spanish. Reload — verify preference persists. Toggle back — verify English returns." },
  { id: "4.12", sectionNum: 4, priority: "high", title: "Facility User redirected to facility home",
    description: "Sign in as a Facility User. Verify they are redirected from / to /facility/[their-site-id] and do not see the generic home page." },
  { id: "4.13", sectionNum: 4, priority: "medium", title: "/facility/$slug 404 for invalid slug",
    description: "Navigate to /facility/does-not-exist. Verify a 404 page is shown, not a crash." },
  { id: "4.14", sectionNum: 4, priority: "low", title: "Footer links are present and correct",
    description: "Verify footer shows: current year copyright, Privacy link (→ /privacy), Terms of Service link (→ /terms), and the 988 crisis line text. Verify both links work." },

  // ── Section 5 — Category Page (User-Facing) ───────────────────────────────
  { id: "5.1",  sectionNum: 5, priority: "critical", title: "Category page loads with all published items",
    description: "Navigate to a category. Verify all published items appear. Verify draft items do not appear. Verify item order matches admin sort order." },
  { id: "5.2",  sectionNum: 5, priority: "critical", title: "Facility-restricted item hidden from wrong facility",
    description: "Create an item in Category A restricted to Facility B. Sign in as Facility A user. Navigate to Category A. Verify the restricted item does not appear." },
  { id: "5.3",  sectionNum: 5, priority: "high", title: "Facility-restricted item visible to admin",
    description: "Sign in as admin. Navigate to a category with facility-restricted items. Verify all items appear (restricted items show a facility badge). Verify no items are hidden from admins." },
  { id: "5.4",  sectionNum: 5, priority: "high", title: "Video — opens player dialog",
    description: "Click a video item. Verify a modal opens with a <video> element. Verify the video plays. Verify the title is shown in the dialog." },
  { id: "5.5",  sectionNum: 5, priority: "critical", title: "Video — auto-completes at 95% playback",
    description: "Play a video to exactly 95% of its duration. Verify the item is automatically marked 'Watched' without the user tapping anything. Verify the progress badge updates immediately." },
  { id: "5.6",  sectionNum: 5, priority: "critical", title: "Video — resumes from last position",
    description: "Play a video to ~50%. Close the dialog. Reopen the video. Verify playback resumes from approximately the 50% position rather than from 0:00." },
  { id: "5.7",  sectionNum: 5, priority: "high", title: "Video — progress badge shows percentage",
    description: "Play a video to ~40%. Close the dialog. Verify the action badge shows something like '40% watched' — not 'Not watched' and not 'Watched.'" },
  { id: "5.8",  sectionNum: 5, priority: "high", title: "Audio — same behavior as video",
    description: "Repeat tests 5.4–5.7 for an audio item. Verify 'Listened' label instead of 'Watched.'" },
  { id: "5.9",  sectionNum: 5, priority: "high", title: "PDF — opens viewer dialog",
    description: "Click a PDF item. Verify the in-app viewer opens. Verify the PDF renders. Verify multi-page PDFs show navigation controls. Verify page navigation works." },
  { id: "5.10", sectionNum: 5, priority: "critical", title: "PDF — auto-completes at 95% reading time",
    description: "Open a PDF and remain on it for 95% of its estimated reading time (check the duration field in admin). Verify the PDF auto-marks as 'Read.'" },
  { id: "5.11", sectionNum: 5, priority: "high", title: "PDF — manual 'Mark as read' before finishing",
    description: "Open a PDF briefly (e.g. 10% of reading time). Close it. Verify a 'Mark as read' button appears. Click it. Verify the item is marked read with 'Read manually at X%' badge." },
  { id: "5.12", sectionNum: 5, priority: "high", title: "Image — opens and auto-marks complete",
    description: "Click an image item. Verify the image displays. Close the viewer. Verify the item is immediately marked as 'Viewed.'" },
  { id: "5.13", sectionNum: 5, priority: "high", title: "External link — opens and auto-marks complete",
    description: "Click a link-type item. Verify it opens in a new tab. Verify the item is marked as 'Clicked' after the click." },
  { id: "5.14", sectionNum: 5, priority: "high", title: "Worksheet/Article — manual mark as read",
    description: "Click the action badge on a worksheet or article item. Verify it changes from 'Mark as read' to 'Read' with the current date. Verify the category progress ring increases." },
  { id: "5.15", sectionNum: 5, priority: "critical", title: "Exempt item — Acknowledge button and disclaimer",
    description: "Verify an exempt item shows: an info icon (ⓘ) next to the title; 'Acknowledge' as the action button; a disclaimer 'Doesn't count toward your progress.' Click Acknowledge → badge changes to 'Acknowledged.' Refresh → stays 'Acknowledged.'" },
  { id: "5.16", sectionNum: 5, priority: "critical", title: "Exempt item — does NOT count toward ring or stats",
    description: "Note the category ring percentage. Acknowledge an exempt item. Verify the ring does NOT change. Verify the overall progress ring on the dashboard does NOT change. Verify 'Items Completed' stat does NOT increase." },
  { id: "5.17", sectionNum: 5, priority: "high", title: "Exempt item — excluded from denominator",
    description: "In a category with 5 items (1 exempt), verify the header shows 'X of 4' — not 'X of 5.' Verify the exempt item is not counted in the denominator." },
  { id: "5.18", sectionNum: 5, priority: "high", title: "Ratings appear after completion",
    description: "Complete an item. Verify thumbs-up and thumbs-down appear. Rate as Helpful → thumbs-up fills. Rate as Not Helpful → thumbs-down fills, thumbs-up clears. Tap active rating again → rating removed." },
  { id: "5.19", sectionNum: 5, priority: "high", title: "Bookmark toggle",
    description: "Tap the bookmark icon. Verify it fills. Navigate to dashboard Saved tab — item appears. Return to category. Tap bookmark again — it unfills. Navigate to Saved — item is gone." },
  { id: "5.20", sectionNum: 5, priority: "high", title: "Category completion celebration modal",
    description: "Complete the last item in a category. Verify a modal appears with 'You completed [Category Name]' and a congratulatory message. Click 'Keep going.' Verify the modal closes and does not reappear on reload." },
  { id: "5.21", sectionNum: 5, priority: "medium", title: "Type filter works",
    description: "On a category with mixed content types, use the type filter dropdown. Select 'Video.' Verify only video items appear. Select 'All.' Verify all items return." },
  { id: "5.22", sectionNum: 5, priority: "medium", title: "Other categories carousel",
    description: "Verify the 'Other categories' carousel at the bottom shows other published categories (excluding the current one). Verify clicking a card navigates correctly. Verify carousel arrows work." },
  { id: "5.23", sectionNum: 5, priority: "medium", title: "Category 404 for unpublished slug",
    description: "Navigate to /category/draft-category-slug where the category is unpublished. Verify a 404 page appears." },
  { id: "5.24", sectionNum: 5, priority: "medium", title: "Category 404 for nonexistent slug",
    description: "Navigate to /category/totally-made-up-slug. Verify a 404 page appears, not a crash." },
  { id: "5.25", sectionNum: 5, priority: "medium", title: "'New' badge on items",
    description: "Use an item added within the last 7 days that the user hasn't opened. Verify a 'New' badge appears. Open the item. Verify the 'New' badge disappears." },
  { id: "5.26", sectionNum: 5, priority: "medium", title: "Session time tracked during video/audio playback",
    description: "Open a video. Play it for ~1 minute without pausing. Close. Navigate to the individual user report in admin. Verify session time for that item shows approximately 1 minute." },
  { id: "5.27", sectionNum: 5, priority: "high", title: "Language toggle on category page",
    description: "On a category with Spanish translations, toggle to Spanish. Verify category name, tagline, item titles, descriptions, and action badge labels switch to Spanish. Toggle back — verify English returns." },

  // ── Section 6 — User Dashboard ────────────────────────────────────────────
  { id: "6.1",  sectionNum: 6, priority: "critical", title: "Dashboard requires authentication",
    description: "Navigate to /dashboard without being signed in. Verify redirect to /signup?redirect=/dashboard." },
  { id: "6.2",  sectionNum: 6, priority: "high", title: "Resume card appears for in-progress content",
    description: "Partially complete a video (e.g. 40%). Navigate to the dashboard. Verify the 'Pick Up Where You Left Off' resume card appears at the top of My Progress showing the video title and progress. Click it — verify navigation to the correct item." },
  { id: "6.3",  sectionNum: 6, priority: "medium", title: "Resume card disappears when all content completed",
    description: "Complete every available item. Verify the resume card no longer appears on the dashboard." },
  { id: "6.4",  sectionNum: 6, priority: "high", title: "Overall progress ring — weighted calculation",
    description: "With a fresh account, open a video and watch to 60%. Verify the overall ring is not 0% — it reflects the partial progress. Complete the video. Verify the ring increases to reflect 100% for that item." },
  { id: "6.5",  sectionNum: 6, priority: "medium", title: "Overall ring shows checkmark at 100%",
    description: "Complete every available item. Verify the overall ring is solid and shows a checkmark icon instead of '100%.'" },
  { id: "6.6",  sectionNum: 6, priority: "high", title: "Stat cards — Items Completed",
    description: "Note 'Items Completed.' Mark an item complete. Return to dashboard. Verify count increased by 1. Acknowledge an exempt item. Verify the count does NOT change." },
  { id: "6.7",  sectionNum: 6, priority: "medium", title: "Stat cards — Day Streak",
    description: "Verify the streak count matches the number of consecutive days the account has been logged in. If you can simulate a gap by checking login history, do so." },
  { id: "6.8",  sectionNum: 6, priority: "high", title: "Monthly summary — appears with activity",
    description: "Complete at least one item this calendar month. Verify the monthly summary card appears. Expand it. Verify it shows the correct item count and time spent. Verify the delta label compares to last month's count." },
  { id: "6.9",  sectionNum: 6, priority: "medium", title: "Monthly summary — hidden with no activity",
    description: "Use a fresh account with no completions this month. Verify the monthly summary card does not appear." },
  { id: "6.10", sectionNum: 6, priority: "medium", title: "Monthly summary — achievements this month",
    description: "Earn an achievement this month. Expand the monthly summary. Verify the achievement icon appears in the third column with a tooltip showing the achievement name." },
  { id: "6.11", sectionNum: 6, priority: "medium", title: "Engagement tier — appears only with sufficient users",
    description: "On a facility with fewer than 10 users, verify the engagement tier card does not appear (or shows no percentile). On a facility with 10+ users, verify the tier and percentile are shown." },
  { id: "6.12", sectionNum: 6, priority: "high", title: "Category accordion — progress rings correct",
    description: "Expand a category accordion. Verify the category ring shows the correct weighted progress. Complete an item. Verify the ring updates without a page reload." },
  { id: "6.13", sectionNum: 6, priority: "critical", title: "Category accordion — exempt items excluded from count",
    description: "In a category with 5 items (1 exempt), verify the accordion header shows 'X of 4 items' — not 'X of 5.' Acknowledge the exempt item. Verify the 'X of 4' denominator does not change." },
  { id: "6.14", sectionNum: 6, priority: "high", title: "Category completion celebration fires from dashboard",
    description: "From the dashboard, click through to a category page. Complete the last item. Return to the dashboard. Verify the completion modal fires." },
  { id: "6.15", sectionNum: 6, priority: "high", title: "Saved tab — bookmarked items appear",
    description: "Bookmark two items from different categories. Navigate to Saved tab. Verify both appear with category icon and name. Verify clicking an item navigates to the correct category page and item." },
  { id: "6.16", sectionNum: 6, priority: "high", title: "Saved tab — removing a bookmark",
    description: "On the Saved tab, click the bookmark icon to remove an item. Verify it disappears immediately. Refresh. Verify it remains gone." },
  { id: "6.17", sectionNum: 6, priority: "medium", title: "Saved tab — empty state",
    description: "Remove all bookmarks. Navigate to Saved tab. Verify an empty state message appears prompting the user to save resources." },
  { id: "6.18", sectionNum: 6, priority: "high", title: "Achievements tab — all 13 show",
    description: "Navigate to the Achievements tab. Verify all 13 achievement badges appear. Verify earned badges are in accent color. Verify unearned badges are dimmed. Verify the 'X of 13 earned' count is accurate." },
  { id: "6.19", sectionNum: 6, priority: "critical", title: "Achievement unlocks correctly: First Resource",
    description: "Use a fresh account. Complete the first item. Verify: a toast appears 'Achievement unlocked: First Resource'; the Achievements tab count increases by 1; the 'First Resource' badge is lit up." },
  { id: "6.20", sectionNum: 6, priority: "high", title: "Achievement: items_10 (10 Resources)",
    description: "Complete 10 non-exempt items. Verify the '10 Resources' achievement toast fires after the 10th completion." },
  { id: "6.21", sectionNum: 6, priority: "high", title: "Achievement: program_1 (Category Graduate)",
    description: "Complete every non-exempt item in a category. Verify the 'Category Graduate' achievement fires." },
  { id: "6.22", sectionNum: 6, priority: "medium", title: "Achievement: time_5h (5 Hours In)",
    description: "Accumulate 5 hours of active session time across items. Verify the '5 Hours In' achievement fires." },
  { id: "6.23", sectionNum: 6, priority: "medium", title: "Achievement: streak_7 (7-Day Streak)",
    description: "Log in on 7 consecutive days. Verify the '7-Day Streak' achievement fires." },
  { id: "6.24", sectionNum: 6, priority: "critical", title: "Achievements NOT awarded for exempt items",
    description: "Acknowledge an exempt item. Verify the 'First Resource' achievement does NOT fire (exempt items don't count toward achievement milestones)." },
  { id: "6.25", sectionNum: 6, priority: "medium", title: "Account tab — profile information",
    description: "Navigate to the Account tab. Verify username, full name, facility, and join date are shown correctly." },
  { id: "6.26", sectionNum: 6, priority: "high", title: "Account tab — update security questions",
    description: "Click 'Update security questions.' Choose 2 new questions with new answers. Submit. Verify a success toast. Sign out. Go through password reset with the new answers. Verify reset succeeds." },
  { id: "6.27", sectionNum: 6, priority: "critical", title: "Security questions locked until set up",
    description: "Create a new account and skip security question setup. Navigate to the Progress tab. Verify it is locked with a prompt to set up questions. Verify you cannot access content until questions are configured." },
  { id: "6.28", sectionNum: 6, priority: "high", title: "Forced password reset on first login",
    description: "Sign in to an account with the must_reset_password flag set. Verify a password reset form appears before dashboard content is accessible. Complete the reset. Verify the flag is cleared and normal access is restored." },

  // ── Section 7 — Admin Access Control ─────────────────────────────────────
  { id: "7.1",  sectionNum: 7, priority: "critical", title: "Unauthenticated access to admin pages redirects",
    description: "While signed out, navigate directly to /admin, /admin/analytics, /admin/users, /admin/messages, /admin/facilities, /admin/ip-allowlist, /admin/audit-log, /admin/errors. Verify each redirects to /signup?redirect=..." },
  { id: "7.2",  sectionNum: 7, priority: "critical", title: "Regular user cannot access any admin page",
    description: "Sign in as a regular user. Navigate directly to /admin. Verify a redirect or 'access required' message — not the admin dashboard. Try all admin URLs listed in 7.1. Verify every attempt fails." },
  { id: "7.3",  sectionNum: 7, priority: "critical", title: "Contributor — content pages accessible",
    description: "Sign in as a contributor. Verify access to /admin/ (categories list), /admin/category/$id (editor), /admin/privacy, /admin/terms." },
  { id: "7.4",  sectionNum: 7, priority: "critical", title: "Contributor — blocked from non-content pages",
    description: "Sign in as a contributor. Navigate directly to /admin/analytics, /admin/users, /admin/messages, /admin/facilities, /admin/ip-allowlist, /admin/audit-log, /admin/errors, /admin/home, /admin/icons-badges, /admin/seed. Verify each is blocked." },
  { id: "7.5",  sectionNum: 7, priority: "critical", title: "Facility User — correct pages accessible",
    description: "Sign in as a Facility User. Verify access to /admin/analytics, /admin/users, /admin/messages. Verify they are redirected away from /admin/ (categories) to /admin/users." },
  { id: "7.6",  sectionNum: 7, priority: "critical", title: "Facility User — blocked from admin-only pages",
    description: "Sign in as a Facility User. Navigate directly to /admin/facilities, /admin/ip-allowlist, /admin/audit-log, /admin/errors, /admin/home, /admin/icons-badges, /admin/seed, /admin/category/$id. Verify all are blocked." },
  { id: "7.7",  sectionNum: 7, priority: "critical", title: "Facility User — data is scoped to their facility only",
    description: "Sign in as Facility User A. Verify analytics shows only Facility A's data; user list shows only Facility A's users; individual user reports show only Facility A's users." },
  { id: "7.8",  sectionNum: 7, priority: "critical", title: "Facility User cannot view other facility users via URL",
    description: "Sign in as Facility User A. Obtain a userId belonging to Facility B. Try to construct a request showing Facility B's user report. Verify the server rejects the request with a 'Forbidden' error." },
  { id: "7.9",  sectionNum: 7, priority: "critical", title: "Server functions enforce access independently of route guards",
    description: "Using browser devtools or a REST client, call a server function directly (e.g. listAdminUsers) while authenticated as a regular user. Verify the call is rejected with a 403 or 'Forbidden' error." },
  { id: "7.10", sectionNum: 7, priority: "high", title: "Admin cannot delete their own account",
    description: "Sign in as an admin. Navigate to Users. Find the current admin's own account. Verify the Delete button is absent or disabled. Verify the bulk delete action does not include the current user." },
  { id: "7.11", sectionNum: 7, priority: "high", title: "Admin cannot revoke their own admin role",
    description: "Sign in as an admin. Find the current user's own account. Verify the role toggle for 'Admin' is disabled or that attempting to disable it shows an error." },

  // ── Section 8 — Admin Content Management ─────────────────────────────────
  { id: "8.1",  sectionNum: 8, priority: "high", title: "Create a new category",
    description: "Click 'New category.' Fill in name, slug, tagline, description. Click Create. Verify: category appears in admin list; NOT visible on public site (if draft); toggle published → appears on home page." },
  { id: "8.2",  sectionNum: 8, priority: "medium", title: "Slug is auto-generated from name",
    description: "Type a category name (e.g. 'My New Category'). Verify the slug field auto-populates as 'my-new-category.' Manually edit the slug. Verify it stops auto-updating." },
  { id: "8.3",  sectionNum: 8, priority: "medium", title: "Duplicate slug is rejected",
    description: "Create a category with a slug that already exists. Verify the form shows an error or the database rejects it with a clear message." },
  { id: "8.4",  sectionNum: 8, priority: "medium", title: "Category drag-and-drop reorder",
    description: "Drag a category to a new position. Verify order updates in the list. Refresh admin page — verify order persists. Visit public home page — verify categories appear in the new order." },
  { id: "8.5",  sectionNum: 8, priority: "medium", title: "Bulk delete categories",
    description: "Enter edit mode. Select 2+ categories. Click 'Delete selected.' Confirm. Verify the categories are removed from the admin list and the public site." },
  { id: "8.6",  sectionNum: 8, priority: "high", title: "Add content item",
    description: "Within a category editor, click the add item button. Fill in title, type, URL, description, duration. Save. Verify the item appears in the category list and on the public category page." },
  { id: "8.7",  sectionNum: 8, priority: "medium", title: "Upload a file — progress bar displays",
    description: "Upload a PDF or video file via the file uploader. Verify the button shows a real-time percentage progress bar. Verify the bar fills smoothly and the URL is populated after upload completes." },
  { id: "8.8",  sectionNum: 8, priority: "medium", title: "Uploading a replacement file deletes the old one",
    description: "Upload a file to an item. Save. Upload a different file to the same item. Verify the old file URL is no longer referenced and the new file is used." },
  { id: "8.9",  sectionNum: 8, priority: "medium", title: "PDF reading time auto-estimation",
    description: "Upload a text-based PDF. Verify the duration field is automatically populated with an estimated reading time. Verify the estimate is reasonable relative to the PDF's page count and word density." },
  { id: "8.10", sectionNum: 8, priority: "high", title: "Published / draft toggle",
    description: "Publish an item — verify it appears for users. Toggle to draft — verify it disappears from the public category page. Verify it remains visible in the admin editor." },
  { id: "8.11", sectionNum: 8, priority: "medium", title: "Item drag-and-drop reorder within category",
    description: "Drag an item to a new position. Verify the order changes. Verify the public category page reflects the new order." },
  { id: "8.12", sectionNum: 8, priority: "high", title: "Facility restriction on category",
    description: "Restrict a category to Facility A. Sign in as Facility B user — verify the category does not appear. Sign in as Facility A user — verify it is visible." },
  { id: "8.13", sectionNum: 8, priority: "high", title: "Facility restriction on individual item",
    description: "Restrict a specific item within a shared category to Facility A. Sign in as Facility B user — verify that item is not shown. Sign in as Facility A user — verify the item appears." },
  { id: "8.14", sectionNum: 8, priority: "critical", title: "Exempt from tracking toggle",
    description: "Mark an item as 'Exempt from tracking.' Save. As a user: verify 'Acknowledge' button appears; verify disclaimer appears; verify acknowledging does not affect ring/stats/achievements; verify item does NOT appear in analytics engagement section." },
  { id: "8.15", sectionNum: 8, priority: "medium", title: "Custom content type — create",
    description: "In the type dropdown, type a new type name (e.g. 'Workbook') and create it. Verify it appears in the dropdown, in Icons & Badges, and as a type filter on the public category page." },
  { id: "8.16", sectionNum: 8, priority: "medium", title: "Custom content type — delete",
    description: "Delete a custom type from the Icons & Badges page. Verify all items using that type are reassigned to 'Article.' Verify the type no longer appears in the dropdown." },
  { id: "8.17", sectionNum: 8, priority: "medium", title: "AI copy generation",
    description: "Enter a category name and click 'Auto-generate tagline & description.' Verify a suggested tagline and description are filled in within a few seconds without error." },
  { id: "8.18", sectionNum: 8, priority: "medium", title: "AI translation (category)",
    description: "Fill in English fields for a category. Click 'Add Spanish translation.' Verify Spanish fields are populated with plausible translations. Verify English fields are not overwritten." },
  { id: "8.19", sectionNum: 8, priority: "medium", title: "AI translation (content item)",
    description: "Fill in English fields for a content item. Click 'Add Spanish translation.' Verify Spanish title, description, and source are populated. Verify English fields are unchanged." },
  { id: "8.20", sectionNum: 8, priority: "medium", title: "Translation status badge accuracy",
    description: "Verify the translation badge shows: 'Complete' when all English fields have Spanish equivalents; 'Partially translated' when some are missing; 'Needs ES' when no Spanish fields are filled despite English content." },
  { id: "8.21", sectionNum: 8, priority: "medium", title: "Seed content CSV import",
    description: "Prepare a CSV with valid category_slug and title columns. Import via the seed page. Verify items appear in the correct categories. Verify the preview table shows validation errors before import. Verify invalid rows don't block valid ones." },

  // ── Section 9 — Admin User Management ────────────────────────────────────
  { id: "9.1",  sectionNum: 9, priority: "high", title: "User list loads and paginates",
    description: "Navigate to /admin/users. Verify all sections load (Admins, Testers, Facility Staff, Registered Users). Verify the registered users list paginates (10 per page). Verify page navigation works." },
  { id: "9.2",  sectionNum: 9, priority: "high", title: "Search filters by name/username/PIN",
    description: "Type a partial username in the search box. Verify results update after ~300ms (debounced). Verify only matching users appear. Clear the search — verify all users return." },
  { id: "9.3",  sectionNum: 9, priority: "high", title: "Facility filter",
    description: "Select a specific facility from the facility filter. Verify only users from that facility appear. Select 'All' — verify all users return." },
  { id: "9.4",  sectionNum: 9, priority: "medium", title: "New user badge in navigation",
    description: "Sign up a new user. Without visiting the Users page, sign in as admin. Verify the AdminNav shows a badge count next to 'Users.' Navigate to the Users page. Verify the badge clears on the next visit." },
  { id: "9.5",  sectionNum: 9, priority: "high", title: "Set user password",
    description: "Expand a user's row. Enter a new password (min 8 chars). Save. Sign out. Sign in as that user with the new password. Verify success." },
  { id: "9.6",  sectionNum: 9, priority: "medium", title: "Send password reset email",
    description: "Click 'Send password reset email' for a user with an email address. Verify a success toast appears." },
  { id: "9.7",  sectionNum: 9, priority: "high", title: "Clear security questions",
    description: "Clear security questions for a user. Verify a success toast. Verify the password reset flow fails at Step 1 for that user (fake questions returned). Verify the user can re-enroll from their Account tab." },
  { id: "9.8",  sectionNum: 9, priority: "high", title: "Create admin/contributor account",
    description: "Click 'Add user' → select 'Admin or Contributor.' Enter email and password. Assign a role. Submit. Verify account appears in Admins & Contributors. Sign in with those credentials — verify correct admin panel access." },
  { id: "9.9",  sectionNum: 9, priority: "medium", title: "Create tester account",
    description: "Create a tester account. Verify it appears in Testers section. Sign in as the tester. Verify tester can browse content like a regular user. Verify tester activity does NOT appear in analytics reports." },
  { id: "9.10", sectionNum: 9, priority: "high", title: "Create facility user account",
    description: "Create a facility user account for Facility A. Verify must_reset_password is set. Sign in as the new facility user. Verify the password reset is required. Complete it. Verify access is scoped to Facility A." },
  { id: "9.11", sectionNum: 9, priority: "high", title: "Role assignment — single role invariant",
    description: "Find a user with the 'Admin' role. Assign 'Contributor' to them. Verify the 'Admin' role is automatically removed. Verify the user now has only 'Contributor' access." },
  { id: "9.12", sectionNum: 9, priority: "high", title: "Delete a single user",
    description: "Delete a regular user. Verify confirmation dialog appears. Confirm. Verify the user no longer appears in the list. Verify the user cannot sign in." },
  { id: "9.13", sectionNum: 9, priority: "medium", title: "Bulk delete users",
    description: "Enter edit mode. Select 3 users. Click 'Delete selected.' Confirm. Verify all 3 are removed. Verify none can sign in." },
  { id: "9.14", sectionNum: 9, priority: "critical", title: "Facility User can only see their facility's users",
    description: "Sign in as Facility User A. Navigate to /admin/users. Verify only Facility A's regular users appear. Verify Admins and Testers sections are hidden. Verify the facility filter is locked to Facility A." },
  { id: "9.15", sectionNum: 9, priority: "high", title: "Facility User can set password for their facility's user",
    description: "Sign in as Facility User A. Set the password for a Facility A regular user. Verify success. Verify the regular user can sign in with the new password." },
  { id: "9.16", sectionNum: 9, priority: "critical", title: "Facility User cannot manage Facility B's users",
    description: "Sign in as Facility User A. Obtain a userId for a Facility B user. Try to call setUserPassword via the API. Verify the server returns a 'Forbidden' error — blocked server-side." },

  // ── Section 10 — Admin Analytics ──────────────────────────────────────────
  { id: "10.1",  sectionNum: 10, priority: "high", title: "Overall tab loads and shows correct totals",
    description: "Navigate to the Analytics Overall tab. Verify summary cards show non-zero values. Verify time range switching (Last 7 days, 30 days, etc.) updates the displayed numbers." },
  { id: "10.2",  sectionNum: 10, priority: "high", title: "Category accordion in usage report",
    description: "Expand a category in the usage report. Verify per-item stats appear: open count, completion rate, avg time, helpful/not-helpful, bookmarks. Verify exempt items are NOT listed." },
  { id: "10.3",  sectionNum: 10, priority: "high", title: "Most & Least Engaged Content",
    description: "Verify the Most/Least Engaged section shows two tabs. Switch between them. Verify Most shows highest completion rates; Least shows lowest. Verify only items with sufficient data are included." },
  { id: "10.4",  sectionNum: 10, priority: "critical", title: "By Facility tab — data scoped correctly",
    description: "Select Facility A from the picker. Verify all metrics reflect only Facility A's users. Switch to Facility B. Verify numbers change to reflect Facility B's data." },
  { id: "10.5",  sectionNum: 10, priority: "medium", title: "By Facility tab — facility ranking shown",
    description: "Select a specific facility. Verify the facility's ranking in the overall comparison is shown (e.g. '#3 of 5 facilities by completion rate')." },
  { id: "10.6",  sectionNum: 10, priority: "high", title: "Users tab — user list with engagement data",
    description: "Select a facility in the Users tab. Verify registered users appear with last login date and engagement tier. Verify synthetic/tester accounts do not appear." },
  { id: "10.7",  sectionNum: 10, priority: "high", title: "Individual user report — correct section order",
    description: "Click a user to open their report. Verify sections appear in this order: stat cards → monthly summary → engagement tier → achievements → category list." },
  { id: "10.8",  sectionNum: 10, priority: "high", title: "Individual user report — exempt items with disclaimer",
    description: "Open a user report for a user who has acknowledged an exempt item. Verify the exempt item appears with 'Acknowledged' badge and a disclaimer. Verify it is NOT counted in 'X of Y items completed.'" },
  { id: "10.9",  sectionNum: 10, priority: "medium", title: "Individual user report — ratings and bookmarks visible",
    description: "Open a user report for a user who has rated and bookmarked items. Verify ratings appear on the relevant items. Verify bookmarked items show the bookmark indicator." },
  { id: "10.10", sectionNum: 10, priority: "medium", title: "Export CSV — Usage report",
    description: "Click Export CSV on the Overall usage report. Verify a CSV downloads. Open it. Verify the header row is present. Verify category and item data appear with correct columns." },
  { id: "10.11", sectionNum: 10, priority: "medium", title: "Export CSV — Facility comparison",
    description: "Click the CSV export button in the Facility Comparison section. Verify a CSV downloads with one row per facility, containing user counts, completion rate, time spent, bookmarks, and ratings." },
  { id: "10.12", sectionNum: 10, priority: "medium", title: "Export CSV — Individual user progress",
    description: "Click 'Export CSV' on an individual user report. Verify columns: Category, Item Title, Read, Read On, Progress, Time Spent, Bookmarked, Rating. Verify category appears only on the summary row; item rows have blank category column." },
  { id: "10.13", sectionNum: 10, priority: "medium", title: "Export CSV — Facility users list",
    description: "Click 'Export CSV' on the facility user list. Verify a CSV downloads with one row per user, including name, username, PIN, signup date, last login, engagement tier." },
  { id: "10.14", sectionNum: 10, priority: "high", title: "Export CSV — Bulk facility progress",
    description: "Select a facility. Click 'Export All Progress (CSV).' Verify: one row per user×item; items grouped by category in display order; user-level fields shown only on first row per user; Category shown only on first item per group. Columns: First Name, Last Name, Username, PIN, Last Login, Items Completed, Time Spent (hrs), Category, Item Title, Completed, Completed On, Progress %, Time on Item (min), Bookmarked, Rating." },
  { id: "10.15", sectionNum: 10, priority: "medium", title: "Bulk progress export — not available for all facilities",
    description: "In the Users tab, select 'All facilities.' Verify the 'Export All Progress' button is not shown — only 'Export CSV' (the user list)." },
  { id: "10.16", sectionNum: 10, priority: "medium", title: "Manual nightly refresh trigger (admin only)",
    description: "Sign in as admin. Click the 'Refresh' button in the analytics header. Verify a success toast and the refresh timestamp updates. Sign in as Facility User — verify the refresh button is not visible." },
  { id: "10.17", sectionNum: 10, priority: "critical", title: "Tester data excluded from analytics",
    description: "Sign in as a tester. Complete several items and spend 10+ minutes in content. Sign in as admin. Verify the tester's completions and time do NOT appear in Overall analytics or any facility's usage report." },
  { id: "10.18", sectionNum: 10, priority: "critical", title: "Facility User analytics are facility-scoped server-side",
    description: "Sign in as Facility User A. Verify only Facility A's data is shown. Attempt to switch the facility filter to Facility B via browser devtools. Verify the server rejects the override and returns Facility A's data regardless." },

  // ── Section 11 — Admin Messages ───────────────────────────────────────────
  { id: "11.1", sectionNum: 11, priority: "high", title: "Site-wide message — enable and save",
    description: "Navigate to Messages. Enable the site-wide message. Enter text. Save. Visit the main page as a user — verify the banner appears. Disable the message — verify the banner is gone." },
  { id: "11.2", sectionNum: 11, priority: "critical", title: "Facility message — Facility User can only edit their own",
    description: "Sign in as Facility User A. Navigate to Messages. Verify only Facility A's message editor is shown. Try to submit with a different facility value via devtools. Verify the server rejects the override." },
  { id: "11.3", sectionNum: 11, priority: "medium", title: "Spanish translation field",
    description: "Enter a message in English and Spanish. Save. Switch UI to Spanish — verify the Spanish version appears in the banner. Switch to English — verify the English version appears." },
  { id: "11.4", sectionNum: 11, priority: "medium", title: "Updated message re-shows to users who dismissed",
    description: "Enable a message. Sign in as a user. Dismiss the banner. Update the message text in admin. Sign in as the user again. Verify the banner reappears." },
  { id: "11.5", sectionNum: 11, priority: "medium", title: "Auto-expand Spanish section when translation exists",
    description: "Save a message with a Spanish translation. Reload the Messages page. Verify the Spanish section is automatically expanded (not collapsed)." },

  // ── Section 12 — Admin Facilities ─────────────────────────────────────────
  { id: "12.1", sectionNum: 12, priority: "high", title: "Create a new facility",
    description: "Click Add Facility. Enter a label and Site ID. Submit. Verify the facility appears in the list. Verify a public URL (?site=[siteId]) resolves correctly and shows the facility's home page." },
  { id: "12.2", sectionNum: 12, priority: "medium", title: "Site ID generates the correct URL slug",
    description: "Create a facility with Site ID 'Test Facility 01'. Verify the derived slug is 'test_facility_01' (lowercased, spaces → underscores, special chars stripped). Verify the URL works." },
  { id: "12.3", sectionNum: 12, priority: "medium", title: "Duplicate Site ID is rejected",
    description: "Try to create two facilities with the same Site ID. Verify the second attempt is rejected with an appropriate error." },
  { id: "12.4", sectionNum: 12, priority: "medium", title: "Edit facility label",
    description: "Edit a facility's label. Verify the new label appears everywhere the facility name is shown (user dropdown, admin analytics picker, reports, etc.)." },
  { id: "12.5", sectionNum: 12, priority: "medium", title: "Delete a facility",
    description: "Delete a facility. Verify it no longer appears in facility dropdowns, the analytics picker, or the sign-up form. Verify users previously assigned to that facility still exist." },
  { id: "12.6", sectionNum: 12, priority: "medium", title: "Facility list shows user count",
    description: "Verify each facility row shows the count of registered users. Create a new user at a facility. Verify the count increases." },

  // ── Section 13 — Admin System Tools ──────────────────────────────────────
  { id: "13.1",  sectionNum: 13, priority: "high", title: "Audit log — password reset is logged",
    description: "Set a user's password from the admin Users page. Navigate to the Audit Log. Verify a user.password_reset entry appears with the correct actor, target user, and timestamp." },
  { id: "13.2",  sectionNum: 13, priority: "high", title: "Audit log — role grant/revoke is logged",
    description: "Grant or revoke a role from a user. Verify the audit log shows a user.role_grant or user.role_revoke entry." },
  { id: "13.3",  sectionNum: 13, priority: "high", title: "Audit log — user creation is logged",
    description: "Create a new admin/contributor account. Verify a user.create entry appears in the audit log." },
  { id: "13.4",  sectionNum: 13, priority: "medium", title: "Audit log — free-text search",
    description: "Enter a username or email in the audit log search box. Verify only entries matching that user (as actor or target) appear." },
  { id: "13.5",  sectionNum: 13, priority: "medium", title: "Audit log — Facility User sees scoped entries only",
    description: "Sign in as Facility User A. Navigate to the audit log. Verify only entries involving Facility A's users appear. Verify Facility B entries are not shown." },
  { id: "13.6",  sectionNum: 13, priority: "medium", title: "Error log — client errors appear",
    description: "Intentionally trigger a JavaScript error (or call reportError(new Error('test')) from the browser console). Navigate to the admin Error Log. Verify a 'client' source entry appears." },
  { id: "13.7",  sectionNum: 13, priority: "medium", title: "Error log — clear old entries",
    description: "Click 'Clear older than 30 days.' Verify a success toast. Verify entries newer than 30 days are not deleted. Verify entries older than 30 days are gone." },
  { id: "13.8",  sectionNum: 13, priority: "medium", title: "Icons & Badges — change variant color",
    description: "Change the color of the 'New' badge variant. Click Save Changes. Verify the 'New' badge on content items reflects the new color. Verify reloading the admin page shows the saved color." },
  { id: "13.9",  sectionNum: 13, priority: "medium", title: "Icons & Badges — change content type icon",
    description: "Change the icon for the 'Video' content type. Save. Verify Video badges across the platform use the new icon." },
  { id: "13.10", sectionNum: 13, priority: "medium", title: "Icons & Badges — category icon assignment",
    description: "Change a category's icon or color from the Icons & Badges page. Save. Verify the category card on the home page and the category accordion on the dashboard reflect the new icon and color." },
  { id: "13.11", sectionNum: 13, priority: "critical", title: "IP Allowlist — restriction blocks non-listed IP",
    description: "Enable IP restrictions. Add one IP to the allowlist that is NOT your current IP. Verify the site shows the 'Access restricted' page with your IP address. Add your IP. Verify access is restored within ~30 seconds." },
  { id: "13.12", sectionNum: 13, priority: "critical", title: "IP Allowlist — toggle disables all checks",
    description: "Enable IP restrictions with a non-matching IP on the list. Verify you are blocked. Toggle restrictions OFF. Verify you can access the site immediately (within the ~30 second cache window)." },
  { id: "13.13", sectionNum: 13, priority: "medium", title: "IP Allowlist — blocked page shows user's IP",
    description: "While blocked, verify the blocked page displays the visitor's actual IP address. Verify it is not showing 0.0.0.0 or null." },

  // ── Section 14 — Multilingual (EN / ES) ───────────────────────────────────
  { id: "14.1",  sectionNum: 14, priority: "high", title: "Language toggle persists across navigation",
    description: "Switch to Spanish. Navigate to the home page, then a category, then the dashboard. Verify all pages remain in Spanish throughout the session." },
  { id: "14.2",  sectionNum: 14, priority: "medium", title: "Language toggle persists across sessions",
    description: "Switch to Spanish. Sign out. Close and reopen the browser. Navigate to the platform. Verify Spanish is still active (stored in localStorage)." },
  { id: "14.3",  sectionNum: 14, priority: "medium", title: "Language parameter in URL",
    description: "Navigate to /?language=es. Verify the UI switches to Spanish. Navigate to /?language=en. Verify it returns to English." },
  { id: "14.4",  sectionNum: 14, priority: "high", title: "Content item action badges are translated",
    description: "Switch to Spanish. On the category page, verify: 'Acknowledge' → 'Confirmar'; 'Acknowledged' → 'Confirmado'; 'Mark as read' → 'Marcar como leído'; 'Watched' → 'Visto'; 'Listened' → 'Escuchado'; 'Doesn't count toward your progress' → 'No cuenta para tu progreso'." },
  { id: "14.5",  sectionNum: 14, priority: "medium", title: "Exempt item tooltip is translated",
    description: "Switch to Spanish. Hover the (ⓘ) icon on an exempt item. Verify the tooltip is in Spanish ('Este elemento es informativo y no cuenta para tu progreso')." },
  { id: "14.6",  sectionNum: 14, priority: "medium", title: "Category names and taglines display in Spanish",
    description: "Switch to Spanish. Verify categories with Spanish translations show translated names on the home page and category page. Verify categories without translations still show English names." },
  { id: "14.7",  sectionNum: 14, priority: "medium", title: "Content item titles and descriptions in Spanish",
    description: "Switch to Spanish for a category with translated items. Verify item titles and descriptions show Spanish text. Verify the fallback to English for items without translations." },
  { id: "14.8",  sectionNum: 14, priority: "medium", title: "Duration strings are translated",
    description: "Switch to Spanish. Verify duration strings like '5 min read' become '5 min de lectura', '20 min watch' becomes '20 min de video', etc." },
  { id: "14.9",  sectionNum: 14, priority: "medium", title: "Achievement toasts are in the user's language",
    description: "Switch to Spanish. Complete an item that unlocks an achievement. Verify the toast notification text is in Spanish." },
  { id: "14.10", sectionNum: 14, priority: "high", title: "Dashboard and all tabs in Spanish",
    description: "Switch to Spanish. Navigate through all dashboard tabs. Verify no English text bleeds through in labels, headings, or button text that has a Spanish translation." },
  { id: "14.11", sectionNum: 14, priority: "medium", title: "Sign-up form and errors in Spanish",
    description: "Switch to Spanish. Navigate to the sign-up page. Verify all labels, placeholders, and error messages are in Spanish." },

  // ── Section 15 — Analytics Data Integrity ────────────────────────────────
  { id: "15.1", sectionNum: 15, priority: "high", title: "Session time is real (not estimated)",
    description: "Open an article item. Actively interact for exactly 2 minutes. Close the item. Pull the individual user report in admin. Verify 'Time on Item' shows approximately 2 minutes — not 0 and not the admin-estimated duration." },
  { id: "15.2", sectionNum: 15, priority: "high", title: "Inactivity stops the timer",
    description: "Open an item. Do nothing for 90+ seconds (no scrolling, clicking, or typing). Then interact for 1 more minute. Close the item. Verify the session time recorded is ~1 minute — not 2.5 minutes." },
  { id: "15.3", sectionNum: 15, priority: "medium", title: "Completion rate calculation",
    description: "Open an item without completing it. Verify the item's open count increases in analytics. Complete the item. Verify the complete count increases and the completion rate (completions/opens × 100) is correct." },
  { id: "15.4", sectionNum: 15, priority: "critical", title: "Exempt items excluded from overall completion rate",
    description: "Verify exempt items are not included in the overall completion rate in the usage report. Acknowledge an exempt item. Verify the overall rate is unaffected." },
  { id: "15.5", sectionNum: 15, priority: "medium", title: "Bookmark and rating counts are accurate",
    description: "Bookmark an item as User A. Rate it as User B. Pull the usage report. Verify the item shows bookmark_count=1 and the appropriate thumbs up/down count." },
  { id: "15.6", sectionNum: 15, priority: "medium", title: "Monthly summary counts match actual completions",
    description: "Note current month completions from the admin report. Compare to what the user sees on their dashboard monthly summary card. Verify the numbers match." },
  { id: "15.7", sectionNum: 15, priority: "critical", title: "Exempt items excluded from monthly summary",
    description: "Note the monthly summary item count. Acknowledge an exempt item. Verify the monthly summary count does NOT increase." },
  { id: "15.8", sectionNum: 15, priority: "critical", title: "Achievements not triggered by exempt items",
    description: "Use a fresh account. Acknowledge an exempt item as the only action. Verify the 'First Resource' achievement does NOT fire." },
  { id: "15.9", sectionNum: 15, priority: "critical", title: "Progress ring excludes exempt items from denominator",
    description: "In a category with 10 items (2 exempt), complete 4 trackable items. Verify the ring shows 4/8 = 50% — not 4/10 = 40%." },

  // ── Section 16 — Mobile & Responsive ─────────────────────────────────────
  { id: "16.1", sectionNum: 16, priority: "medium", title: "Navigation menu collapses on mobile",
    description: "On a narrow screen (<768px), verify the nav links collapse into a hamburger button. Tap the button — verify the mobile menu opens with all links. Tap a link — verify the menu closes." },
  { id: "16.2", sectionNum: 16, priority: "medium", title: "On-screen keyboard appears on mobile sign-up",
    description: "On a touch device (or browser emulation with coarse pointer), open sign-up. Tap a text field. Verify the custom on-screen keyboard appears at the bottom. Verify the native keyboard does NOT appear. Verify typing works correctly." },
  { id: "16.3", sectionNum: 16, priority: "medium", title: "On-screen keyboard — Shift key works",
    description: "On the on-screen keyboard, tap Shift. Verify the key highlights. Tap a letter — verify it is capitalized. Verify Shift auto-releases after one character." },
  { id: "16.4", sectionNum: 16, priority: "medium", title: "On-screen keyboard — Enter submits form",
    description: "Fill in all sign-up fields using the on-screen keyboard. Tap Enter. Verify the form submits." },
  { id: "16.5", sectionNum: 16, priority: "medium", title: "On-screen keyboard — dismiss button",
    description: "Tap the X button in the top-right of the on-screen keyboard. Verify the keyboard hides. Tap a field again — verify the keyboard reappears." },
  { id: "16.6", sectionNum: 16, priority: "medium", title: "Home page grid is responsive",
    description: "Resize the browser from desktop to mobile. Verify the category grid reflows: 4 columns → 3 → 2 → 1 column. Verify no cards are cut off or overflow horizontally." },
  { id: "16.7", sectionNum: 16, priority: "medium", title: "Admin panel is usable on tablet",
    description: "On a tablet-sized screen, verify the admin category list, user list, and analytics page are usable without horizontal scrolling (or scroll gracefully where appropriate)." },
  { id: "16.8", sectionNum: 16, priority: "medium", title: "PDF viewer fits screen",
    description: "Open a PDF on a mobile screen. Verify the PDF viewer fills the available width without content overflowing or requiring horizontal scroll. Verify page navigation controls are tappable." },
  { id: "16.9", sectionNum: 16, priority: "medium", title: "Category accordion items are tappable",
    description: "On mobile, expand a category accordion on the dashboard. Verify each item's action badge and bookmark/rating controls are large enough to tap accurately without triggering adjacent elements." },

  // ── Section 17 — Security & Edge Cases ───────────────────────────────────
  { id: "17.1",  sectionNum: 17, priority: "critical", title: "SQL injection in search",
    description: "Steps: In the admin user search, type each of these strings one at a time and press Enter: '; DROP TABLE users; -- and ' OR 1=1 --\n\n✅ Pass: The search field treats the input as plain text. No error appears, the page does not crash, the app continues to work normally, and no unexpected data from other users appears in the results. The database is unaffected — all other pages still load correctly after the test." },
  { id: "17.2",  sectionNum: 17, priority: "critical", title: "XSS in user-generated content",
    description: "Steps: In the admin content editor, paste the following into a title field: <script>alert('xss')</script>. Save. Then sign in as a regular user and navigate to that category page.\n\n✅ Pass: No alert box or popup appears. The text is displayed literally on the page (the angle brackets and word 'script' are visible as plain text), or the tags are stripped entirely. No browser console errors related to script execution. The page loads and functions normally." },
  { id: "17.3",  sectionNum: 17, priority: "critical", title: "PostgREST injection via filter values",
    description: "Steps: In the admin user search box, type: ilike.%admin% and press Enter.\n\n✅ Pass: The search treats this as a literal text search string. The results either show nothing (no user with that exact string in their name) or show a user whose name literally contains those characters. No admin accounts are unexpectedly surfaced. The page does not crash. The behavior is identical to searching for any other nonsense string." },
  { id: "17.4",  sectionNum: 17, priority: "high", title: "Session expiry",
    description: "Steps: Sign in as a regular user. Open browser devtools → Application tab → Local Storage → find the Supabase entry → delete the access_token value. Then try to navigate to the dashboard or mark an item complete.\n\n✅ Pass: You are redirected to the sign-in page, OR a toast message appears asking you to sign in again. You do not see a raw error like '401 Unauthorized' or a blank broken page. The app handles the expired session gracefully and gives you a clear path to sign back in." },
  { id: "17.5",  sectionNum: 17, priority: "critical", title: "Server function called without auth header",
    description: "Steps: Open browser devtools → Network tab. Find any server function request (they go to /_server/...). Right-click it → Copy as fetch. Paste into the Console tab. Remove the Authorization header from the copied fetch call. Run it.\n\n✅ Pass: The response status is 401 or the response body contains an error message like 'Unauthorized: No authorization header provided.' No user data, profile info, or any database content is returned in the response." },
  { id: "17.6",  sectionNum: 17, priority: "critical", title: "Server function called with invalid token",
    description: "Steps: Open browser devtools → Console. Run: fetch('/_server/getMyProfile', { method: 'POST', headers: { 'Authorization': 'Bearer FAKE_INVALID_TOKEN_12345', 'content-type': 'application/json' }, body: '{}' }).then(r => r.text()).then(console.log)\n\n✅ Pass: The response contains an error message like 'Unauthorized: Invalid token.' The status code is 401 or similar. No profile data or user information is returned. The response is NOT a 500 internal server error (which would indicate the error was unhandled)." },
  { id: "17.7",  sectionNum: 17, priority: "high", title: "Security headers present on responses",
    description: "Steps: Open browser devtools → Network tab. Click on any page load request (the main HTML document). Click on it. Scroll down to 'Response Headers' in the right panel.\n\n✅ Pass: You can see ALL FOUR of these headers listed:\n• strict-transport-security (value contains max-age=)\n• x-content-type-options with value nosniff\n• referrer-policy with value strict-origin-when-cross-origin\n• content-security-policy (value is a long string starting with default-src 'self')" },
  { id: "17.8",  sectionNum: 17, priority: "critical", title: "RLS prevents cross-user data access",
    description: "Steps: Sign in as a regular user (User A). Open browser devtools → Console. Type exactly this and press Enter:\nsupabase.from('user_content_progress').select('*').then(r => console.log(r.data))\n\n✅ Pass: The console output shows an array where every single row has a user_id that matches User A's own ID. You see zero rows belonging to any other user. If you sign in as User B and repeat the test, you only see User B's rows. The total number of rows visible matches only what that user has personally completed." },
  { id: "17.9",  sectionNum: 17, priority: "high", title: "Draft category is not accessible via direct URL",
    description: "Steps: In admin, note a category's slug (e.g. 'recovery-resources'). Unpublish that category. Sign in as a regular user (or sign out). Navigate directly to /category/recovery-resources in the browser address bar.\n\n✅ Pass: A '404 — Page not found' page appears. You see the 404 heading and a Go Home button. No category content, item list, or partial data from that category is visible anywhere on the page." },
  { id: "17.10", sectionNum: 17, priority: "high", title: "Draft item is not returned in category query",
    description: "Steps: In admin, unpublish one content item inside a published category. Sign in as a regular user. Navigate to that category page.\n\n✅ Pass: The unpublished item is completely absent from the list — it does not appear with a 'draft' label or greyed out; it is simply not there. The item count shown on the category card on the home page does not include it. There is no way to open or access it." },
  { id: "17.11", sectionNum: 17, priority: "critical", title: "Facility-restricted item not accessible via URL manipulation",
    description: "Steps: In admin, restrict a content item to Facility B only. Note that item's ID (visible in the admin URL when editing it). Sign in as a Facility A user. Open browser devtools → Console. Run:\nsupabase.from('content_items').select('*').eq('id', 'PASTE_ITEM_ID_HERE').then(r => console.log(r.data))\n\n✅ Pass: The console output shows an empty array []. No data for that item is returned. The item also does not appear anywhere on Facility A's category pages. There is no way for a Facility A user to see, open, or interact with that item." },
  { id: "17.12", sectionNum: 17, priority: "medium", title: "Rate limiting on log-error endpoint",
    description: "Steps: Open browser devtools → Console. Run this to send 101 requests:\nfor(let i=0;i<101;i++) fetch('/api/public/log-error',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:'rate-limit-test'})})\nThen go to Admin → Errors and count the entries created from this test.\n\n✅ Pass: All 101 requests return HTTP status 204 in the Network tab — no 429 or 400 responses. Fewer than 101 error log entries are created from this test (the extra requests were silently dropped without logging). Nothing in the response body reveals that rate limiting is active." },
  { id: "17.13", sectionNum: 17, priority: "medium", title: "Log-error always returns 204",
    description: "Steps: Open browser devtools → Console. Run:\nfetch('/api/public/log-error',{method:'POST',headers:{'content-type':'application/json'},body:'{{not valid json at all'}).then(r=>console.log('Status:',r.status))\n\n✅ Pass: The console shows 'Status: 204'. The Network tab confirms the response status is 204 with an empty body. You do NOT see 400, 422, or any other status code. No validation error details are exposed that could tell an attacker what the expected format is." },
  { id: "17.14", sectionNum: 17, priority: "high", title: "Audit log is append-only",
    description: "Steps: Navigate to Admin → Audit Log. Look through every button, icon, and control on the page carefully.\n\n✅ Pass: There is no Delete button, trash icon, checkbox for bulk delete, or any other UI element that allows removing individual audit log entries. Every recorded action remains permanently visible. The only controls available are for filtering and searching — not for deleting." },
  { id: "17.15", sectionNum: 17, priority: "medium", title: "Bookmark toggle is idempotent",
    description: "Steps: Navigate to a category page with a content item. Click the bookmark icon on an item twice as fast as possible (double-click speed).\n\n✅ Pass: The bookmark icon settles into one consistent final state — either filled (saved) or unfilled (not saved). No error toast appears. The item either appears or does not appear in the Saved tab consistently with the icon state. Refreshing the page shows the same state — it has not flipped back and forth." },
  { id: "17.16", sectionNum: 17, priority: "medium", title: "Concurrent rating change",
    description: "Steps: Complete a content item so ratings appear. Click 'Helpful.' Immediately (within half a second, before the first click finishes processing) click 'Not helpful.'\n\n✅ Pass: After both clicks settle, only one rating is active — 'Not helpful' (thumbs down filled, thumbs up unfilled). No error toast appears. Refreshing the page shows the same state. The rating is not stuck in a loading state." },
  { id: "17.17", sectionNum: 17, priority: "medium", title: "Category page with 0 published items",
    description: "Steps: In admin, create a new published category and intentionally add no items (or unpublish all items in an existing category). Navigate to that category's public page as a user.\n\n✅ Pass: A clean empty state message appears — something like 'No content yet — check back soon.' The page does not show a blank white area, JavaScript error, or crash. The navigation bar, back button, and page layout all look normal." },
  { id: "17.18", sectionNum: 17, priority: "medium", title: "404 page preserves facility URL context",
    description: "Steps: Visit the app through a facility URL so ?site=yourSiteId appears in the URL. Navigate to a page that doesn't exist — for example, type /this-page-does-not-exist in the address bar.\n\n✅ Pass: The 404 page appears with a 'Go home' button. Click it. The URL you land on includes ?site=yourSiteId — you are returned to the facility home page, not the generic home page without the facility context. Your session context is preserved." },

  // ── Section 18 — Performance & Stability ─────────────────────────────────
  { id: "18.1", sectionNum: 18, priority: "medium", title: "First page load time",
    description: "On a fresh browser (no cache), load the main page. Verify it renders within a reasonable time (<3 seconds on a standard connection). Verify no console errors appear on first load." },
  { id: "18.2", sectionNum: 18, priority: "medium", title: "PDF viewer lazy loading",
    description: "Load the category page. Open browser devtools → Network. Verify the pdfjs-dist worker bundle is NOT loaded until a PDF item is opened. Open a PDF — verify the worker loads only at that point." },
  { id: "18.3", sectionNum: 18, priority: "medium", title: "Large category with many items",
    description: "Navigate to a category with 20+ items. Verify the page renders all items without error. Verify scrolling is smooth. Verify the type filter works with many items." },
  { id: "18.4", sectionNum: 18, priority: "medium", title: "Admin category list with many categories",
    description: "If the platform has 15+ categories, verify the admin list renders all of them without performance degradation. Verify drag-and-drop still works." },
  { id: "18.5", sectionNum: 18, priority: "medium", title: "Analytics report with large dataset",
    description: "With 100+ users and 1000+ completions in the data, load the analytics Overall tab. Verify the report loads within a reasonable time. Verify no timeout errors. Verify CSV export completes for a facility with many users." },
  { id: "18.6", sectionNum: 18, priority: "high", title: "Bulk facility progress export completeness",
    description: "Export the bulk progress CSV for a facility. Open it in a spreadsheet app. Verify the row count equals (number of users) × (number of published items visible to that facility). Verify no rows are missing or truncated." },
];

// Helper: tests grouped by section
export function getTestsBySection(): Map<number, QATest[]> {
  const map = new Map<number, QATest[]>();
  for (const test of QA_TESTS) {
    const arr = map.get(test.sectionNum) ?? [];
    arr.push(test);
    map.set(test.sectionNum, arr);
  }
  return map;
}

export const PRIORITY_COLORS: Record<TestPriority, string> = {
  critical: "text-red-600 bg-red-50 border-red-200",
  high:     "text-orange-600 bg-orange-50 border-orange-200",
  medium:   "text-yellow-600 bg-yellow-50 border-yellow-200",
  low:      "text-green-600 bg-green-50 border-green-200",
};

export const PRIORITY_LABELS: Record<TestPriority, string> = {
  critical: "🔴 Critical",
  high:     "🟠 High",
  medium:   "🟡 Medium",
  low:      "🟢 Low",
};

export const STATUS_COLORS: Record<TestStatus, string> = {
  untested: "text-muted-foreground bg-muted border-border",
  pass:     "text-green-700 bg-green-50 border-green-300",
  fail:     "text-red-700 bg-red-50 border-red-300",
  blocked:  "text-yellow-700 bg-yellow-50 border-yellow-300",
  skipped:  "text-muted-foreground bg-muted/60 border-border",
};

export const STATUS_LABELS: Record<TestStatus, string> = {
  untested: "Untested",
  pass:     "Pass",
  fail:     "Fail",
  blocked:  "Blocked",
  skipped:  "Skipped",
};

export const STATUS_ICONS: Record<TestStatus, string> = {
  untested: "○",
  pass:     "✓",
  fail:     "✗",
  blocked:  "⊘",
  skipped:  "—",
};
