/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FacilitySlugRouteImport } from './routes/facility.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTermsRouteImport } from './routes/admin.terms'
import { Route as AdminSeedRouteImport } from './routes/admin.seed'
import { Route as AdminPrivacyRouteImport } from './routes/admin.privacy'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminIpAllowlistRouteImport } from './routes/admin.ip-allowlist'
import { Route as AdminIconsBadgesRouteImport } from './routes/admin.icons-badges'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminFacilitiesRouteImport } from './routes/admin.facilities'
import { Route as AdminErrorsRouteImport } from './routes/admin.errors'
import { Route as AdminCertificateRouteImport } from './routes/admin.certificate'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiPublicLogErrorRouteImport } from './routes/api/public/log-error'
import { Route as AdminCategoryIdRouteImport } from './routes/admin.category.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FacilitySlugRoute = FacilitySlugRouteImport.update({
  id: '/facility/$slug',
  path: '/facility/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTermsRoute = AdminTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeedRoute = AdminSeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrivacyRoute = AdminPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIpAllowlistRoute = AdminIpAllowlistRouteImport.update({
  id: '/ip-allowlist',
  path: '/ip-allowlist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIconsBadgesRoute = AdminIconsBadgesRouteImport.update({
  id: '/icons-badges',
  path: '/icons-badges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificateRoute = AdminCertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicLogErrorRoute = ApiPublicLogErrorRouteImport.update({
  id: '/api/public/log-error',
  path: '/api/public/log-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoryIdRoute = AdminCategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/certificate': typeof AdminCertificateRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/icons-badges': typeof AdminIconsBadgesRoute
  '/admin/ip-allowlist': typeof AdminIpAllowlistRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/privacy': typeof AdminPrivacyRoute
  '/admin/seed': typeof AdminSeedRoute
  '/admin/terms': typeof AdminTermsRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/facility/$slug': typeof FacilitySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/category/$id': typeof AdminCategoryIdRoute
  '/api/public/log-error': typeof ApiPublicLogErrorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/certificate': typeof AdminCertificateRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/icons-badges': typeof AdminIconsBadgesRoute
  '/admin/ip-allowlist': typeof AdminIpAllowlistRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/privacy': typeof AdminPrivacyRoute
  '/admin/seed': typeof AdminSeedRoute
  '/admin/terms': typeof AdminTermsRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/facility/$slug': typeof FacilitySlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/category/$id': typeof AdminCategoryIdRoute
  '/api/public/log-error': typeof ApiPublicLogErrorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/certificate': typeof AdminCertificateRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/icons-badges': typeof AdminIconsBadgesRoute
  '/admin/ip-allowlist': typeof AdminIpAllowlistRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/privacy': typeof AdminPrivacyRoute
  '/admin/seed': typeof AdminSeedRoute
  '/admin/terms': typeof AdminTermsRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/facility/$slug': typeof FacilitySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/category/$id': typeof AdminCategoryIdRoute
  '/api/public/log-error': typeof ApiPublicLogErrorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/certificate'
    | '/admin/errors'
    | '/admin/facilities'
    | '/admin/home'
    | '/admin/icons-badges'
    | '/admin/ip-allowlist'
    | '/admin/messages'
    | '/admin/privacy'
    | '/admin/seed'
    | '/admin/terms'
    | '/admin/users'
    | '/category/$slug'
    | '/facility/$slug'
    | '/admin/'
    | '/admin/category/$id'
    | '/api/public/log-error'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/certificate'
    | '/admin/errors'
    | '/admin/facilities'
    | '/admin/home'
    | '/admin/icons-badges'
    | '/admin/ip-allowlist'
    | '/admin/messages'
    | '/admin/privacy'
    | '/admin/seed'
    | '/admin/terms'
    | '/admin/users'
    | '/category/$slug'
    | '/facility/$slug'
    | '/admin'
    | '/admin/category/$id'
    | '/api/public/log-error'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/certificate'
    | '/admin/errors'
    | '/admin/facilities'
    | '/admin/home'
    | '/admin/icons-badges'
    | '/admin/ip-allowlist'
    | '/admin/messages'
    | '/admin/privacy'
    | '/admin/seed'
    | '/admin/terms'
    | '/admin/users'
    | '/category/$slug'
    | '/facility/$slug'
    | '/admin/'
    | '/admin/category/$id'
    | '/api/public/log-error'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  FacilitySlugRoute: typeof FacilitySlugRoute
  ApiPublicLogErrorRoute: typeof ApiPublicLogErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/facility/$slug': {
      id: '/facility/$slug'
      path: '/facility/$slug'
      fullPath: '/facility/$slug'
      preLoaderRoute: typeof FacilitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/terms': {
      id: '/admin/terms'
      path: '/terms'
      fullPath: '/admin/terms'
      preLoaderRoute: typeof AdminTermsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seed': {
      id: '/admin/seed'
      path: '/seed'
      fullPath: '/admin/seed'
      preLoaderRoute: typeof AdminSeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/privacy': {
      id: '/admin/privacy'
      path: '/privacy'
      fullPath: '/admin/privacy'
      preLoaderRoute: typeof AdminPrivacyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ip-allowlist': {
      id: '/admin/ip-allowlist'
      path: '/ip-allowlist'
      fullPath: '/admin/ip-allowlist'
      preLoaderRoute: typeof AdminIpAllowlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/icons-badges': {
      id: '/admin/icons-badges'
      path: '/icons-badges'
      fullPath: '/admin/icons-badges'
      preLoaderRoute: typeof AdminIconsBadgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facilities': {
      id: '/admin/facilities'
      path: '/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/errors': {
      id: '/admin/errors'
      path: '/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificate': {
      id: '/admin/certificate'
      path: '/certificate'
      fullPath: '/admin/certificate'
      preLoaderRoute: typeof AdminCertificateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/log-error': {
      id: '/api/public/log-error'
      path: '/api/public/log-error'
      fullPath: '/api/public/log-error'
      preLoaderRoute: typeof ApiPublicLogErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/category/$id': {
      id: '/admin/category/$id'
      path: '/category/$id'
      fullPath: '/admin/category/$id'
      preLoaderRoute: typeof AdminCategoryIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCertificateRoute: typeof AdminCertificateRoute
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminIconsBadgesRoute: typeof AdminIconsBadgesRoute
  AdminIpAllowlistRoute: typeof AdminIpAllowlistRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPrivacyRoute: typeof AdminPrivacyRoute
  AdminSeedRoute: typeof AdminSeedRoute
  AdminTermsRoute: typeof AdminTermsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCategoryIdRoute: typeof AdminCategoryIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCertificateRoute: AdminCertificateRoute,
  AdminErrorsRoute: AdminErrorsRoute,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminIconsBadgesRoute: AdminIconsBadgesRoute,
  AdminIpAllowlistRoute: AdminIpAllowlistRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPrivacyRoute: AdminPrivacyRoute,
  AdminSeedRoute: AdminSeedRoute,
  AdminTermsRoute: AdminTermsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCategoryIdRoute: AdminCategoryIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  FacilitySlugRoute: FacilitySlugRoute,
  ApiPublicLogErrorRoute: ApiPublicLogErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
