/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminIpAllowlistRouteImport } from './routes/admin.ip-allowlist'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminCertificateRouteImport } from './routes/admin.certificate'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCategoryIdRouteImport } from './routes/admin.category.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIpAllowlistRoute = AdminIpAllowlistRouteImport.update({
  id: '/ip-allowlist',
  path: '/ip-allowlist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificateRoute = AdminCertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoryIdRoute = AdminCategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/certificate': typeof AdminCertificateRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/ip-allowlist': typeof AdminIpAllowlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/category/$id': typeof AdminCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/certificate': typeof AdminCertificateRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/ip-allowlist': typeof AdminIpAllowlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/category/$id': typeof AdminCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/certificate': typeof AdminCertificateRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/ip-allowlist': typeof AdminIpAllowlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/category/$id': typeof AdminCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/analytics'
    | '/admin/certificate'
    | '/admin/home'
    | '/admin/ip-allowlist'
    | '/category/$slug'
    | '/admin/'
    | '/admin/category/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/analytics'
    | '/admin/certificate'
    | '/admin/home'
    | '/admin/ip-allowlist'
    | '/category/$slug'
    | '/admin'
    | '/admin/category/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/analytics'
    | '/admin/certificate'
    | '/admin/home'
    | '/admin/ip-allowlist'
    | '/category/$slug'
    | '/admin/'
    | '/admin/category/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategorySlugRoute: typeof CategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ip-allowlist': {
      id: '/admin/ip-allowlist'
      path: '/ip-allowlist'
      fullPath: '/admin/ip-allowlist'
      preLoaderRoute: typeof AdminIpAllowlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificate': {
      id: '/admin/certificate'
      path: '/certificate'
      fullPath: '/admin/certificate'
      preLoaderRoute: typeof AdminCertificateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/category/$id': {
      id: '/admin/category/$id'
      path: '/category/$id'
      fullPath: '/admin/category/$id'
      preLoaderRoute: typeof AdminCategoryIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCertificateRoute: typeof AdminCertificateRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminIpAllowlistRoute: typeof AdminIpAllowlistRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCategoryIdRoute: typeof AdminCategoryIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCertificateRoute: AdminCertificateRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminIpAllowlistRoute: AdminIpAllowlistRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCategoryIdRoute: AdminCategoryIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CategorySlugRoute: CategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
