// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function getSupabaseCredentials() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Set them in your .env file.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };
}

function createSupabaseClient() {
  const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = getSupabaseCredentials();

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      // localStorage is only available in the browser; fall back to undefined
      // during SSR so the client can still be constructed without crashing.
      storage: typeof window !== "undefined" ? localStorage : undefined,
      // Browser client persists and auto-refreshes the session so users stay
      // signed in across page reloads without manual token management.
      persistSession: true,
      autoRefreshToken: true,
      // Off by default: /auth/confirmed parses #access_token itself and
      // decides explicitly whether to sign the browser in (see that route).
      // Auto-detection would sign the recovery link's session in globally
      // the instant the page loads, before anyone has set a new password.
      detectSessionInUrl: false,
    },
  });
}

/**
 * A throwaway client that never touches localStorage or fires the shared
 * app's onAuthStateChange listeners — used by the password-recovery flow to
 * call updateUser without signing the browser into the account app-wide.
 * Each call returns a fresh instance; discard it after use.
 */
export function createEphemeralSupabaseClient() {
  const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = getSupabaseCredentials();

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Lazy singleton via Proxy — same pattern as client.server.ts. Defers client
// creation until first use so env vars are guaranteed to be available.
// Import like: import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
